     
      SUBROUTINE EXPDEN(DTRUNC,DFULL,NORB,NCOMP,LABEL,IDROP,NOCC,
     &                  IUHF)
C
C THIS ROUTINE EXPANDS THE DENSITY MATRIX FOR CASES IN WHICH MOS
C  HAVE BEEN DROPPED.   THE SCOPY AT THE BOTTOM OF THE ROUTINE IS
C  OK BECAUSE NORB*NORBS FLOATING POINT WORDS HAVE BEEN ALLOCATED 
C  FOR DTRUNC SO THERE IS NO OVERWRITING.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*6 LABEL
      DIMENSION DTRUNC(NCOMP,NCOMP),DFULL(NORB,NORB),IDROP(NORB)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      Z=2.0
      IF(IUHF.EQ.1)Z=1.0
      CALL ZERO(DFULL,NORB*NORB)
      CALL GETREC(20,'JOBARC',LABEL,NORB,IDROP)
      ICOUNT=0
      DO 10 I=1,NORB
       IF(IDROP(I).EQ.0)THEN
        ICOUNT=ICOUNT+1
        JCOUNT=0 
        DO 20 J=1,I
         IF(IDROP(J).EQ.0)THEN
          JCOUNT=JCOUNT+1
          X=DTRUNC(ICOUNT,JCOUNT)
          DFULL(I,J)=X
          DFULL(J,I)=X
         ENDIF
20      CONTINUE
       ELSE
        IF(IDROP(I).EQ.-1)THEN
         write(6,*)' STUCK ',Z,' IN ',I,',',I
         DFULL(I,I)=Z
        ENDIF
       ENDIF 
10    CONTINUE
c YAU : old
c     CALL ICOPY(NORB*NORB*IINTFP,DFULL,1,DTRUNC,1)
c YAU : new
      CALL DCOPY(NORB*NORB,DFULL,1,DTRUNC,1)
c YAU : end
      RETURN
      END
