
      SUBROUTINE DRVPLD(ICORE,MAXCOR,NORBS)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION PLDENS(3)
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      IMXATM=50
      IONE=1
      I000=1
      I010=I000+IINTFP*NORBS*NORBS
      I020=I010+IINTFP*NORBS*NORBS
      I030=I020+IINTFP*NORBS*NORBS
      I040=I030+IINTFP*NORBS*NORBS
      IATOM=0
      IRWND=0
      CALL GETREC(20,'JOBARC','NATOMS  ',IONE,NATOM)
      CALL GETREC(20,'JOBARC','MAP2ZMAT',NATOM,ICORE(I040))
30    CALL SEEKLB('    DX  ',IERR,IRWND)
      IF(IERR.NE.0)RETURN
      IRWND=1
      IF(IATOM.EQ.0)WRITE(LUOUT,1000)
      IATOM=IATOM+1
      CALL COMPPR(PLDENS(1),ICORE,ICORE(I030),NORBS,.TRUE.)
      CALL SEEKLB('    DY  ',IERR,IRWND)
      CALL COMPPR(PLDENS(2),ICORE,ICORE(I030),NORBS,.TRUE.)
      CALL SEEKLB('    DZ  ',IERR,IRWND)
      CALL COMPPR(PLDENS(3),ICORE,ICORE(I030),NORBS,.TRUE.)
      WRITE(LUOUT,1001)ICORE(I040+IATOM-1),(PLDENS(I),I=1,3)
      GOTO 30
1000  FORMAT(T3,' <q/r**3> terms ',/,T11,'Z-matrix',/,
     &T12,'center',T28,'<qx/r**3>',T42,'<qy/r**3>',T56,'<qz/r**3>')
1001  FORMAT(T13,I3,T22,F15.10,T36,F15.10,T50,F15.10)
      END 
