
      SUBROUTINE DRVPOT(SCR, NATOM, NORBS, NUMATOM)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      DOUBLE PRECISION EPOT
      DIMENSION SCR(4*NORBS*NORBS), NATOM(NUMATOM)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      IMXATM=50
      IONE=1
      I000=1
      I010=I000+NORBS*NORBS
      I020=I010+NORBS*NORBS
      I030=I020+NORBS*NORBS
      I040=I030+NORBS*NORBS
      IATOM=0
      IRWND=0
      CALL GETREC(20,'JOBARC','MAP2ZMAT',NUMATOM,NATOM)
30    CALL SEEKLB('   1/R  ',IERR,IRWND)
      IF(IERR.NE.0)RETURN
      IRWND=1
      IF(IATOM.EQ.0)WRITE(LUOUT,1000)
      IATOM=IATOM+1
      CALL COMPPR(EPOT, SCR, SCR(I030), NORBS, .TRUE.)
      WRITE(LUOUT,2000)NATOM(IATOM),EPOT
      GOTO 30
1000  FORMAT(T3,' Electrostatic potential at atomic centers ',/,
     &T11,'Z-matrix',T48,'Potential',/,T12,'center',T49,'[<1/r>]')
2000  FORMAT(T13,I3,T43,F15.10)
      END 
