      SUBROUTINE FILLDHF2(SCFOCC,DMO,NCOMP,IOCC,NBAS)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION DMO(NCOMP,NCOMP)
      DIMENSION IOCC(8),NBAS(8)
C
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
C
      IOFF=0
      DO 1 IRREP=1,NIRREP
C
       DO 100 I=1,IOCC(IRREP)
        IX=I+IOFF
        DMO(IX,IX)=SCFOCC
100    CONTINUE
       IOFF=IOFF+NBAS(IRREP)
1     CONTINUE
C
      RETURN
      END
