      SUBROUTINE FILLDHF(SCFOCC,DMO,NCOMP,NOCC) 
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION DMO(NCOMP,NCOMP)
C
      DO 100 IOCC=1,NOCC
       DMO(IOCC,IOCC)=SCFOCC
100   CONTINUE
C
      RETURN
      END
