      SUBROUTINE DRAOLAD(ICORE,MAXCOR,IUHF,TAU,TAU2,IRREPX,LISTFLAG,
     &                   LSTMO,LSTMOINC,LSTAO,LSTAOINC)
C
C DRIVER FOR AO-BASED PARTICLE-PARTICLE LADDER CONTRACTION
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      LOGICAL TAU,TAU2
      COMMON /FLAGS/ IFLAGS(100)
C
      CALL AOLADLST(IUHF,LISTFLAG,IRREPX)
      CALL T2TOAO(ICORE,MAXCOR,IUHF,TAU,TAU2,LSTMO,LSTAO,IRREPX)
      IF(IFLAGS(95).EQ.1)THEN
       CALL AOLAD2(ICORE,MAXCOR,IUHF,TAU,IRREPX,LSTAO,LSTAOINC)
      ELSE
       CALL AOLAD3(ICORE,MAXCOR,IUHF,TAU,IRREPX,LSTAO,LSTAOINC)
      ENDIF
      CALL Z2TOMO(ICORE,MAXCOR,IUHF,TAU,IRREPX,LSTMO,LSTMOINC,
     &            LSTAOINC,.FALSE.)
c      IF (SING) CALL ZIAAO(ICORE,MAXCOR,IUHF,IRREPX,90)
C
      RETURN
      END
