      SUBROUTINE DT2INT2(ICORE,MAXCOR,IUHF,IRREPX,ISIDE,
     &                   LISTIJKL,LISTABCD,
     &                   LISTAIBJ,LISTT2,LISTT2IN,LISTT2RS,
     &                   LSTT2RNG)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM
      DIMENSION ICORE(MAXCOR)
      LOGICAL DISCO,INCREM,WSPIN,THREEBOD
      COMMON/FLAGS/IFLAGS(100)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      DATA ONE,ONEM /1.0D0,-1.0D0/
C
C SET UP LADDER CONTRACTIONS
C
      CALL DLADDER(ICORE,MAXCOR,IUHF,IRREPX,1,LISTT2,
     &             LISTIJKL,LISTT2IN,ISIDE)
      IF(ISIDE.EQ.1)CALL MODIFYT2(ICORE,MAXCOR,IUHF,IRREPX,ONE)
      IF(IFLAGS(93).EQ.2)THEN
       CALL DRAOLAD(ICORE,MAXCOR,IUHF,.FALSE.,.FALSE.,IRREPX,0,
     &              443,460,213,463)
c     &              443,460,413,463)
      ELSEIF(ISYTYP(1,233).EQ.5)THEN
       CALL DLADDER2(ICORE,MAXCOR,IUHF,IRREPX,6,LISTT2,
     &               LISTABCD,LISTT2IN,ISIDE)
      ELSE
       CALL DLADDER(ICORE,MAXCOR,IUHF,IRREPX,6,LISTT2,
     &              LISTABCD,LISTT2IN,ISIDE)
      ENDIF
      IF(ISIDE.EQ.1)CALL MODIFYT2(ICORE,MAXCOR,IUHF,IRREPX,ONEM)
      CALL W1LAD  (ICORE,MAXCOR,IUHF,ISIDE,IRREPX)
      CALL MODAIBC(ICORE,MAXCOR,IUHF,ONEM)
      IF(ISIDE.EQ.2)THEN
        CALL L1W1(ICORE,MAXCOR,IUHF,IRREPX,443,90,26,460)
      ELSEIF(ISIDE.EQ.1)THEN
        CALL T1W1(ICORE,MAXCOR,IUHF,IRREPX,443,90,26,460)
      ENDIF 
      CALL MODAIBC(ICORE,MAXCOR,IUHF,ONE)
C
C SET UP RING CONTRACTIONS.  THIS IS SLIGHTLY COMPLICATED.
C
      CALL DFT2INT2(ICORE,MAXCOR,IUHF,IRREPX,LSTT2RNG,LISTT2RS,ISIDE)
C
C THREE BODY TERM
C
      THREEBOD=.true.
      IF(THREEBOD)THEN
C
       IF(ISIDE.EQ.1)THEN
C
C RIGHT-HAND EIGENVECTOR THREE-BODY CONTRIBUTIONS
C
        CALL FORMQ1(IRREPX,ICORE,MAXCOR,IUHF)
        CALL GFORMG2(IRREPX,1,444,14,400,ICORE,MAXCOR,0,ONE,IUHF)
        CALL CNT3BOD2(IRREPX,ICORE,MAXCOR,IUHF,
     &               LISTT2RS)

       ELSEIF(ISIDE.EQ.2)THEN
C
        CALL GFORMG (IRREPX,1,444,44,400,ICORE,MAXCOR,0,
     &               ONE,IUHF)
        CALL GINC1L(IRREPX,ICORE,MAXCOR,IUHF)
        CALL GINC2L(IRREPX,ICORE,MAXCOR,IUHF,LISTT2RS)
       ENDIF
      ENDIF
C
      IF(IUHF.EQ.0)CALL ZEROLIST(ICORE,MAXCOR,441)
      DISCO =ISIDE.EQ.2
      INCREM=.TRUE.
      WSPIN =IUHF.EQ.0
      IF(IUHF.EQ.0)THEN
       CALL DRHFRNG(ICORE,MAXCOR,IUHF,IRREPX,DISCO,INCREM,WSPIN,
     &              LSTT2RNG,LISTAIBJ,LISTT2IN,LISTT2RS,ISIDE)
      ELSE
       CALL DUHFRNG(ICORE,MAXCOR,IUHF,IRREPX,DISCO,INCREM,
     &              LSTT2RNG,LISTAIBJ,LISTT2IN,LISTT2RS,ISIDE)
      ENDIF
C
      RETURN
      END
