      SUBROUTINE FINDMAX(N,V,LENGTH,VALUE,ITMP)
C
C THIS ROUTINE LOCATES THE N LARGEST ELEMENTS BY ABSOLUTE VALUE
C IN THE VECTOR V AND RETURNS THEM IN THE VECTOR VALUE.  ITMP
C HOLDS THE LOCATIONS.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION V(LENGTH),ITMP(N),VALUE(N)
C
      DATA ZILCH /0.0D0/
C
      ICOUNT=0
      DO 10 I=1,N
       ILOC=ISAMAX(LENGTH,V,1)
       VALUE(I)=V(ILOC)
       IF(ABS(VALUE(I)).GT.1.D-8)ICOUNT=ICOUNT+1  
       ITMP(I)=ILOC
       V(ILOC)=ZILCH
10    CONTINUE
C
      CALL SCATTER(ICOUNT,V,ITMP,VALUE)
C
      RETURN
      END
