      SUBROUTINE FINDNTH(LENGTH,ITYPE,V,SCR,NTH,INDEX)
C
C THIS ROUTINE FINDS THE INDEX TO THE NTH LARGEST ENTRY 
C [ITYPE.GE.0] OR NTH SMALLEST ENTRY [ITYPE.LT.0] BY 
C ABSOLUTE VALUE IN THE INPUT VECTOR V.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION V(LENGTH),SCR(LENGTH),ZILCH,LARGE
C
      DATA ZILCH,LARGE /0.0D0,9.9D+38/
C
      CALL SCOPY(LENGTH,V,1,SCR,1)
C
      IF(ITYPE.GE.0)THEN
       DO 10 I=1,NTH
        INDEX=ISAMAX(LENGTH,SCR,1)
        SCR(INDEX)=ZILCH
10     CONTINUE
      ELSE
       DO 20 I=1,NTH
        INDEX=ISAMIN(LENGTH,SCR,1)
        SCR(INDEX)=LARGE
20     CONTINUE
      ENDIF
C
      RETURN
      END
