      SUBROUTINE FNDMAXS(LENGTH,VINPUT,VSPACE,NSPACE,TMP,SMAX,ISMAX,
     &                   RESID)
C
C FINDS LARGEST OVERLAP BETWEEN INPUT VECTOR VINPUT AND BASIS VECTORS
C OF N-DIMENSIONAL VECTOR SPACE VSPACE.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VINPUT(LENGTH),VSPACE(LENGTH,NSPACE),TMP(NSPACE)
C
      DATA ZILCH /0.D0/
C
      SMAX=ZILCH
      DO 10 I=1,NSPACE
       TMP(I)=SDOT(LENGTH,VINPUT,1,VSPACE(1,I),1)
10    CONTINUE
C
      ISMAX=ISAMAX(NSPACE,TMP,1)
      SMAX =TMP(ISMAX)
C
      RETURN
      END
