      SUBROUTINE FNDNDIMS(IUHF, SCR, MAXCOR, NDIMS, IRREPX)
C
C THIS ROUTINE FINDS THE DIMENSION OF THE PROJECTED TDA MATRIX
C
      IMPLICIT NONE
      INTEGER NDIMS, IUHF, NTDA, NUMAA, NUMBB, I,
     &   I000, I010, I020, IRREPX, MAXCOR
      INTEGER IRPDPD, ISYTYP, ID
      DOUBLE PRECISION SCR(MAXCOR)
C
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
       IF(IUHF.EQ.0) THEN
        NTDA=IRPDPD(IRREPX,9)
        CALL GETLST(SCR,1,1,1, 1, 490)
      ELSE
        NUMAA=IRPDPD(IRREPX,ISYTYP(1,19))
        NUMBB=IRPDPD(IRREPX,ISYTYP(1,20))
        NTDA = NUMAA + NUMBB
        I000 = 1
        I010 = I000 + NUMAA
        I020 = I010 + NUMBB
        CALL GETLST(SCR(I000),1,1,1, 1, 490)
        CALL GETLST(SCR(I010),1,1,1, 2, 490)
      ENDIF
C
      NDIMS = 0
      DO I = 1, NTDA
        IF (SCR(I) .GT. 0.5) THEN
          NDIMS = NDIMS + 1
        ENDIF
      ENDDO
C
      RETURN
      END
