      SUBROUTINE FNDNEAR(LENGTH,VINPUT,VEXCLUDE,TEST, TMP,NEXCLUDE,
     &                   VLOCMIN,ILOCMIN,TOL)
C
C LOCATES THE ELEMENT IN A VECTOR WHICH IS CLOSEST TO TEST 
C BUT NOT TOO CLOSE TO THE ELEMENTS IN VEXCLUDE.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VINPUT(LENGTH),VEXCLUDE(NEXCLUDE),TMP(LENGTH)
C
      CALL SCOPY(LENGTH,VINPUT,1,TMP,1)
      DO 10 I=1,NEXCLUDE
       DO 11 J=1,LENGTH
        CALL FNDCLOSE(LENGTH,TMP,VEXCLUDE(I),X,ILOC)
        X2=ABS(VEXCLUDE(I)-TMP(ILOC))
        IF(X2.LT.TOL)TMP(ILOC)=1.D+30
11     CONTINUE
10    CONTINUE
C
      XCLOSE=1.D+30
      DO 20 I=1,LENGTH
       DUMMY=ABS(TMP(I)-TEST)
       IF(DUMMY.LT.XCLOSE)THEN
        ILOCMIN=I
        VLOCMIN=VINPUT(I)
        XCLOSE=DUMMY
       ENDIF 
20    CONTINUE
C
      RETURN
      END
