      SUBROUTINE MODIFYT2(ICORE,MAXCOR,IUHF,IRREPX,FACT)
C
C THIS ROUTINE TAKES THE EOM DOUBLES VECTOR AND FORMS THE QUANTITY
C
C     Z(ab,ij) = R2(ab,ij) + FACT * R1(ai)T1(bj)
C
C     Z(Ab,Ij) = R2(Ab,Ij) + FACT * [R1(AI)*T1(bj) - R1(ai)*T1(BJ)] [ABAB]
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION FACT
      DIMENSION ICORE(MAXCOR),I0T(2),I0C(2)
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C ABAB SPIN CASE
C
      I0T(1)=1
      CALL GETLST(ICORE(I0T(1)),1,1,1,1,90)
      IF(IUHF.NE.0)THEN 
       I0T(2)=I0T(1)+IINTFP*NT(1)
       CALL GETLST(ICORE(I0T(2)),1,1,1,2,90)
      ELSE
       I0T(2)=I0T(1)
      ENDIF
      I0C(1)=I0T(2)+IINTFP*NT(2)
      CALL GETLST(ICORE(I0C(1)),1,1,1,1,490)
      IF(IUHF.NE.0)THEN
       I0C(2)=I0C(1)+IINTFP*IRPDPD(IRREPX,9)
       CALL GETLST(ICORE(I0C(2)),1,1,1,2,490)
      ELSE
       I0C(2)=I0C(1)
      ENDIF
      I000=I0C(2)+IINTFP*IRPDPD(IRREPX,10)
C
      DO 10 IRREPIJ=1,NIRREP
       IRREPAB=DIRPRD(IRREPIJ,IRREPX)
       NUMDST=IRPDPD(IRREPIJ,ISYTYP(2,46))
       DISSYT=IRPDPD(IRREPAB,ISYTYP(1,46))
       CALL GETLST(ICORE(I000),1,NUMDST,1,IRREPIJ,446)
       CALL DTAU(IRREPAB,IRREPIJ,1,IRREPX,ICORE(I000),
     &           ICORE(I0T(1)),ICORE(I0T(2)),
     &           ICORE(I0C(1)),ICORE(I0C(2)),3,FACT)
c       CALL FTAU(ICORE(I000),ICORE(I0T(1)),ICORE(I0C(2)),DISSYT,
c     &           NUMDST,POP(1,1),POP(1,2),VRT(1,1),VRT(1,2),IRREP,
c     &           3,FACT)
c       CALL FTAU(ICORE(I000),ICORE(I0C(1)),ICORE(I0T(2)),DISSYT,
c     &           NUMDST,POP(1,1),POP(1,2),VRT(1,1),VRT(1,2),IRREP,
c     &           3,FACT)
       CALL PUTLST(ICORE(I000),1,NUMDST,1,IRREPIJ,446)
10    CONTINUE
C
      IF(IUHF.NE.0)THEN
       DO 20 ISPIN=1,2
        DO 21 IRREPIJ=1,NIRREP
         IRREPAB=DIRPRD(IRREPIJ,IRREPX)
         NUMDST=IRPDPD(IRREPIJ,ISYTYP(2,43+ISPIN))
         CALL GETLST(ICORE(I000),1,NUMDST,1,IRREPIJ,443+ISPIN)
         CALL DTAU(IRREPAB,IRREPIJ,1,IRREPX,ICORE(I000),
     &             ICORE(I0T(ISPIN)),ICORE(I0T(ISPIN)),
     &             ICORE(I0C(ISPIN)),ICORE(I0C(ISPIN)),ISPIN,FACT)
         CALL PUTLST(ICORE(I000),1,NUMDST,1,IRREPIJ,443+ISPIN)
21      CONTINUE
20     CONTINUE
      ENDIF
C
      RETURN
      END
