      DOUBLE PRECISION FUNCTION SASUM(N,VEC,ISKIP)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VEC(1)
      IOFF=1
      X=0.0D0
      DO 10 I=1,N
       X=X+DABS(VEC(IOFF))
       IOFF=IOFF+ISKIP
10    CONTINUE
      SASUM=X
      RETURN
      END
