      SUBROUTINE CALCC0(IRREPX,EVAL,C,SCR,MAXCOR,IUHF,C0)
C
C THIS CALCULATES THE C0 TERM IN RIGHT-HAND SIDE EIGENVECTORS
C OF THE EFFECTIVE HAMILTONIAN.
C
C THIS TERM IS GIVEN BY 
C
C           -1 
C     C0 = W   [ F(ai) C(ai) + W(ab,ij) C(ab,ij) ]
C
C WHERE W IS THE EIGENVALUE.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION C(*),SCR(MAXCOR)
C
C READ IN <0|Hbar|PHI> MATRIX ELEMENTS
C
      CALL LOADVEC1(IRREPX,SCR,MAXCOR,IUHF,93,0,13,
     &              LENTOT,IUHF.EQ.0)
C
      C0=SDOT(LENTOT,C,1,SCR,1)/EVAL
C
      RETURN
      END
