      SUBROUTINE CALCDEN(IROOT,IRREPX,SCR,MAXCOR,IUHF)
C
C DRIVE THE CALCULATION OF EXCITED STATE TDA DENSITY MATRICES
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SCR(MAXCOR/2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
C READ SINGLE EXCITATION VECTORS
C
      DO 10 ISPIN=1,1+IUHF
       LEN=IRPDPD(IRREPX,8+ISPIN)
       IRREPD=1
       IDOO=1
       IDVV=IDOO+IRPDPD(IRREPD,20+ISPIN)
       IDVO=IDVV+IRPDPD(IRREPD,18+ISPIN)
       IDOV=IDVO+IRPDPD(IRREPD,8+ISPIN)
       IVEC=IDOV+IRPDPD(IRREPD,8+ISPIN)
       ITOP=IVEC+LEN
       CALL ZERO(SCR,ITOP)
C
       CALL GETLST(SCR(IVEC),1,1,1,IRREPX,94)
C
       IOFF=IVEC+(ISPIN-1)*IRPDPD(IRREPX,9)
C
C CALCULATE DENSITY MATRIX CONTRIBUTIONS      
C
       CALL DENS11(SCR(IOFF),SCR(IDOO),SCR(IDVV),IRREPX,ISPIN,IUHF)
       
C
10    CONTINUE
C This and the all the calling routines are borrowed from John
C to debug RPA(D) and commented for standard runs.
CSSSS      Call Mtdaener(SCR,MAXCOR,IUHF,IRREPX,.TRUE.,ETDA)
C
      IONE=1
      CALL PUTREC(20,'JOBARC','IOPTSYM ',IONE,IRREPX)
      
C
      RETURN
      END
