      SUBROUTINE E_T2T32(T3,W,ICORE,
     1                   IADT3,IADW,
     1                   IRPI,IRPJ,IRPK,IRPIJ,IRPIK,IRPJK,IRPIJK,
     1                   I,J,K,IUHF,SCR1,SCR2,SCR3,IRREPX)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION TOL
      DOUBLE PRECISION T3(1),W(1),ICORE(1)
      INTEGER DIRPRD,POP,VRT
      DIMENSION IADW(8),IADT3(8)
      DIMENSION IADT2E(8),LENT2E(8),IADV(8),LENV(8)
      DOUBLE PRECISION SCR1(1),SCR2(1),SCR3(1)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     1                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     1                NF1BB,NF2BB
C
      COMMON /T3OFF/  IOFFVV(8,8,10),IOFFOO(8,8,10),IOFFVO(8,8,4)
      COMMON /T2ILIS/ LIST2I1,LIST2I2,LIST2I3
      COMMON /LISWI/  LWIC11,LWIC12,LWIC13,LWIC14,
     1                LWIC15,LWIC16,LWIC17,LWIC18,
     1                LWIC21,LWIC22,LWIC23,LWIC24,
     1                LWIC25,LWIC26,LWIC27,LWIC28,
     1                LWIC31,LWIC32,LWIC33,
     1                LWIC34,LWIC35,LWIC36,
     1                LWIC37,LWIC38,LWIC39,LWIC40,LWIC41,LWIC42
C
      INDEX(I) = I*(I-1)/2
C
      IF(IUHF.EQ.0) GOTO 500
C
C     ROUTINE TO COMPUTE INCLUSION OF T3 AAB T2 AA AND T2 AB
C
C      AB  AB                      ACD
C     D   T    =    SUM  <BK//CD> T       I<J<K   W(A,CD) * V(CD,B)
C      IJ  IJ       C<D            IJK
C                    K
C
C      AA  AA             AB  AB   AAB
C      AA  AA                      AAB
C
C
C      NOTE : W ARRAY IS W(A,CD), LABELLED BY IRPA.
C
C     SET ADDRESSES FOR EXPANDED T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPIJ)
      IOFFT2E = 1
      DO   50 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,1)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
   50 CONTINUE
C
C     FORM EXPANDED T2 MATRICES. (A,B)
C
      IOFFV = IADT2E(NIRREP) + LENT2E(NIRREP)
      DO   60 IRPCD=1,NIRREP
      IRPA = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPB = DIRPRD(IRPCD,IRPK)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,1).EQ.0) GOTO 60
      LENGTHV = VRT(IRPB,1)*IRPDPD(IRPCD,13)
      IRPBK = DIRPRD(IRPB,IRPK)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPK,IRPBK,4)+(K-1)*VRT(IRPB,1)+1,
     1     VRT(IRPB,1),2,IRPBK,LWIC28)
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,1),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           W(IADW(IRPA)),IRPDPD(IRPCD,13),
     1           ICORE(IOFFV),IRPDPD(IRPCD,13),
     1            0.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
   60 CONTINUE
C
C     ANTISYMMETRIZE THE EXPANDED T2 TO GIVE THE T2 INCREMENT.
C     (A<B) = (A,B) - (B,A).
C
      IADT2 = IADT2E(NIRREP) + LENT2E(NIRREP)
      CALL ZERO(ICORE(IADT2),IRPDPD(IRPAB,1))
      CALL EXPVV(ICORE(IADT2),ICORE(IADT2E(1)),IADT2E,
     1           IOFFVV(1,1,1),IRPAB,1)
C
C     READ CURRENT T2 INCREMENT, ADD THIS PIECE TO IT, AND WRITE SUM
C     BACK TO DISK.
C
      IADT2I = IADT2 + IRPDPD(IRPAB,1)
      IF(IRPIJ.NE.1)THEN
      IJ = (J-1)*POP(IRPI,1) + I
      ELSE
      IJ = INDEX(J-1) + I
      ENDIF
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPIJ,1)+IJ,
     1            1,1,IRPIJ,LIST2I1)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2),
     1            IRPDPD(IRPAB,1), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPIJ,1)+IJ,
     1            1,1,IRPIJ,LIST2I1)
C
C      AB  AB                      ACD
C     D   T    =    SUM  <JB//CD> T
C      IK  IK       C<D            IJK
C                    J
C      AB  AB             AB  AB   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPIK)
      IOFFT2E = 1
      DO  150 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  150 CONTINUE
C
C     FORM T2 MATRICES. (A,B)
C
      IK = (K-1)*POP(IRPI,1) + I
      CALL GETLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
      IOFFV = IADT2E(NIRREP) + LENT2E(NIRREP)
      DO  160 IRPCD=1,NIRREP
      IRPA = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPB = DIRPRD(IRPCD,IRPJ)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 160
C
      LENGTHV = VRT(IRPB,2) * IRPDPD(IRPCD,13)
C
      IRPBJ = DIRPRD(IRPB,IRPJ)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPJ,IRPBJ,3) + (J-1)*VRT(IRPB,2) + 1,
     1     VRT(IRPB,2),2,IRPBJ,LWIC27)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           W(IADW(IRPA)),IRPDPD(IRPCD,13),
     1           ICORE(IOFFV),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  160 CONTINUE
C
      CALL PUTLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
C
C
C      AB  AB                      ACD
C     D   T    =  - SUM  <IB//CD> T
C      JK  JK       C<D            IJK
C                    I
C      AB  AB             AB  AB   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPJK)
      IOFFT2E = 1
      DO  250 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  250 CONTINUE
C
C     FORM T2 MATRICES. (A,B)
C
      JK = (K-1)*POP(IRPJ,1) + J
      CALL GETLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
      IOFFV = IADT2E(NIRREP) + LENT2E(NIRREP)
      DO  260 IRPCD=1,NIRREP
      IRPA = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPB = DIRPRD(IRPCD,IRPI)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 260
C
      LENGTHV = VRT(IRPB,2) * IRPDPD(IRPCD,13)
C
      IRPBI = DIRPRD(IRPB,IRPI)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPI,IRPBI,3) + (I-1)*VRT(IRPB,2) + 1,
     1     VRT(IRPB,2),2,IRPBI,LWIC27)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,13),
     1           -1.0D+00,
     1           W(IADW(IRPA)),IRPDPD(IRPCD,13),
     1           ICORE(IOFFV),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  260 CONTINUE
C
      CALL PUTLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
C
C      AB  AB                      CDB
C     D   T    =    SUM  <AJ//CD> T
C      IK  IK       C<D            IJK
C                    J
C      AB  AB             AA  AA   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR EXPANDED T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPIK)
      IOFFT2E = 1
      DO  350 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  350 CONTINUE
C
C     FORM T2 MATRICES. (A,B)
C
      IK = (K-1)*POP(IRPI,1) + I
      CALL GETLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
      IOFFV = IADT2E(NIRREP) + LENT2E(NIRREP)
      DO  360 IRPCD=1,NIRREP
      IRPB = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPA = DIRPRD(IRPCD,IRPJ)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 360
C
      IRPAJ = DIRPRD(IRPA,IRPJ)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPJ,IRPAJ,1) + (J-1)*VRT(IRPA,1) + 1,
     1     VRT(IRPA,1),2,IRPAJ,LWIC25)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,1),
     1            1.0D+00,
     1           ICORE(IOFFV),IRPDPD(IRPCD,1),
     1           T3(IADT3(IRPB)),IRPDPD(IRPCD,1),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  360 CONTINUE
C
      CALL PUTLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
C      AB  AB                      CDB
C     D   T    =  - SUM  <AI//CD> T
C      JK  JK       C<D            IJK
C                    I
C      AB  AB             AA  AA   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR EXPANDED T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPJK)
      IOFFT2E = 1
      DO  450 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  450 CONTINUE
C
C     FORM T2 MATRICES. (A,B)
C
      JK = (K-1)*POP(IRPJ,1) + J
      CALL GETLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
      IOFFV = IADT2E(NIRREP) + LENT2E(NIRREP)
      DO  460 IRPCD=1,NIRREP
      IRPB = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPA = DIRPRD(IRPCD,IRPI)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 460
C
      IRPAI = DIRPRD(IRPA,IRPI)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPI,IRPAI,1) + (I-1)*VRT(IRPA,1) + 1,
     1     VRT(IRPA,1),2,IRPAI,LWIC25)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,1),
     1           -1.0D+00,
     1           ICORE(IOFFV),IRPDPD(IRPCD,1),
     1           T3(IADT3(IRPB)),IRPDPD(IRPCD,1),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  460 CONTINUE
C
      CALL PUTLST(ICORE(IADT2E(1)),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
      RETURN
C
  500 CONTINUE
C
C     RHF closed-shell specific piece.
C
C      AB  AB                      ACD
C     D   T    =    SUM  <JB//CD> T
C      IK  IK       C<D            IJK
C                    J
C      AB  AB             AB  AB   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPIK)
      IOFFT2E = 1
      DO  510 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  510 CONTINUE
C
      IADT2I = IADT2E(NIRREP) + LENT2E(NIRREP)
      IOFFV  = IADT2I         + IRPDPD(IRPAB,13)
C
C     FORM T2 MATRICES. (A,B)
C
      CALL ZERO(ICORE(IADT2E(1)),IRPDPD(IRPAB,13))
      DO  520 IRPCD=1,NIRREP
      IRPA = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPB = DIRPRD(IRPCD,IRPJ)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 520
C
      LENGTHV = VRT(IRPB,2) * IRPDPD(IRPCD,13)
C
      IRPBJ = DIRPRD(IRPB,IRPJ)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPJ,IRPBJ,4) + (J-1)*VRT(IRPB,2) + 1,
     1     VRT(IRPB,2),2,IRPBJ,LWIC28)
      CALL SYMTR3(IRPBJ,VRT(1,1),VRT(1,2),IRPDPD(IRPBJ,13),
     1            VRT(IRPB,2),ICORE(IOFFV),
     1            SCR1,SCR2,SCR3)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           W(IADW(IRPA)),IRPDPD(IRPCD,13),
     1           ICORE(IOFFV),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  520 CONTINUE
C
      IK = (K-1)*POP(IRPI,1) + I
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
      CALL SYMTR3(IRPAB,VRT(1,1),VRT(1,2),IRPDPD(IRPAB,13),1,
     1            ICORE(IADT2E(1)),SCR1,SCR2,SCR3)
C
      KI = (I-1)*POP(IRPK,2) + K
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPI,IRPIK,6)+KI,
     1            1,1,IRPIK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPI,IRPIK,6)+KI,
     1            1,1,IRPIK,LIST2I3)
C
C      AB  AB                      ACD
C     D   T    =  - SUM  <IB//CD> T
C      JK  JK       C<D            IJK
C                    I
C      AB  AB             AB  AB   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPJK)
      IOFFT2E = 1
      DO  610 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  610 CONTINUE
C
      IADT2I = IADT2E(NIRREP) + LENT2E(NIRREP)
      IOFFV  = IADT2I         + IRPDPD(IRPAB,13)
C
C     FORM T2 MATRICES. (A,B)
C
      CALL ZERO(ICORE(IADT2E(1)),IRPDPD(IRPAB,13))
      DO  620 IRPCD=1,NIRREP
      IRPA = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPB = DIRPRD(IRPCD,IRPI)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 620
C
      LENGTHV = VRT(IRPB,2) * IRPDPD(IRPCD,13)
C
      IRPBI = DIRPRD(IRPB,IRPI)
      CALL GETLST(ICORE(IOFFV),
     1     IOFFVO(IRPI,IRPBI,4) + (I-1)*VRT(IRPB,2) + 1,
     1     VRT(IRPB,2),2,IRPBI,LWIC28)
      CALL SYMTR3(IRPBI,VRT(1,1),VRT(1,2),IRPDPD(IRPBI,13),
     1            VRT(IRPB,2),ICORE(IOFFV),
     1            SCR1,SCR2,SCR3)
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,13),
     1           -1.0D+00,
     1           W(IADW(IRPA)),IRPDPD(IRPCD,13),
     1           ICORE(IOFFV),IRPDPD(IRPCD,13),
     1            1.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  620 CONTINUE
C
      JK = (K-1)*POP(IRPJ,1) + J
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
      CALL SYMTR3(IRPAB,VRT(1,1),VRT(1,2),IRPDPD(IRPAB,13),1,
     1            ICORE(IADT2E(1)),SCR1,SCR2,SCR3)
C
      KJ = (J-1)*POP(IRPK,2) + K
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPJK,6)+KJ,
     1            1,1,IRPJK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPJK,6)+KJ,
     1            1,1,IRPJK,LIST2I3)
C
C      AB  AB                      CDB
C     D   T    =    SUM  <AJ//CD> T
C      IK  IK       C<D            IJK
C                    J
C      AB  AB             AA  AA   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR EXPANDED T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPIK)
      IOFFT2E = 1
      DO  710 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  710 CONTINUE
C
      IADT2I = IADT2E(NIRREP) + LENT2E(NIRREP)
      IOFFV  = IADT2I         + IRPDPD(IRPAB,13)
C
C     FORM T2 MATRICES. (A,B)
C
      CALL ZERO(ICORE(IADT2E(1)),IRPDPD(IRPAB,13))
      DO  720 IRPCD=1,NIRREP
      IRPB = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPA = DIRPRD(IRPCD,IRPJ)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 720
C
      IRPAJ = DIRPRD(IRPA,IRPJ)
        IF(IUHF.EQ.0)THEN
        IOFFV1 = IOFFV + IRPDPD(IRPCD,1) * VRT(IRPA,1)
        CALL GETLST(ICORE(IOFFV1),
     1              IOFFVO(IRPJ,IRPAJ,1) + (J-1)*VRT(IRPA,1) + 1,
     1              VRT(IRPA,1),2,IRPAJ,LWIC28)
        CALL ASSYM3(IRPAJ,VRT(1,1),IRPDPD(IRPCD,1),IRPDPD(IRPCD,13),
     1              VRT(IRPA,1),ICORE(IOFFV),ICORE(IOFFV1),
     1              IOFFVV,1)
        ELSE
        CALL GETLST(ICORE(IOFFV),
     1              IOFFVO(IRPJ,IRPAJ,1) + (J-1)*VRT(IRPA,1) + 1,
     1              VRT(IRPA,1),2,IRPAJ,LWIC25)
        ENDIF
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,1),
     1            1.0D+00,
     1           ICORE(IOFFV),IRPDPD(IRPCD,1),
     1           T3(IADT3(IRPB)),IRPDPD(IRPCD,1),
     1            0.0D+00,
     1           ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  720 CONTINUE
C
      IK = (K-1)*POP(IRPI,1) + I
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPK,IRPIK,5)+IK,
     1            1,1,IRPIK,LIST2I3)
C
      CALL SYMTR3(IRPAB,VRT(1,1),VRT(1,2),IRPDPD(IRPAB,13),1,
     1            ICORE(IADT2E(1)),SCR1,SCR2,SCR3)
C
      KI = (I-1)*POP(IRPK,2) + K
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPI,IRPIK,6)+KI,
     1            1,1,IRPIK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPI,IRPIK,6)+KI,
     1            1,1,IRPIK,LIST2I3)
C
C      AB  AB                      CDB
C     D   T    =  - SUM  <AI//CD> T
C      JK  JK       C<D            IJK
C                    I
C      AB  AB             AA  AA   AAB
C      AB  AB                      AAB
C
C     SET ADDRESSES FOR EXPANDED T2 MATRICES. (A,B)
C
      IRPAB = DIRPRD(IRREPX,IRPJK)
      IOFFT2E = 1
      DO  810 IRPB=1,NIRREP
      IRPA = DIRPRD(IRPB,IRPAB)
      LENT2E(IRPB) = VRT(IRPA,1) * VRT(IRPB,2)
      IF(IRPB.EQ.1)THEN
      IADT2E(IRPB) = IOFFT2E
      ELSE
      IADT2E(IRPB) = IADT2E(IRPB-1) + LENT2E(IRPB-1)
      ENDIF
  810 CONTINUE
C
      IADT2I = IADT2E(NIRREP) + LENT2E(NIRREP)
      IOFFV  = IADT2I         + IRPDPD(IRPAB,13)
C
C     FORM T2 MATRICES. (A,B)
C
      CALL ZERO(ICORE(IADT2E(1)),IRPDPD(IRPAB,13))
      DO  820 IRPCD=1,NIRREP
      IRPB = DIRPRD(IRPCD,DIRPRD(IRREPX,IRPIJK))
      IRPA = DIRPRD(IRPCD,IRPI)
      IF(VRT(IRPA,1).EQ.0.OR.VRT(IRPB,2).EQ.0) GOTO 820
C
      IRPAI = DIRPRD(IRPA,IRPI)
        IF(IUHF.EQ.0)THEN
        IOFFV1 = IOFFV + IRPDPD(IRPCD,1) * VRT(IRPA,1)
        CALL GETLST(ICORE(IOFFV1),
     1              IOFFVO(IRPI,IRPAI,1) + (I-1)*VRT(IRPA,1) + 1,
     1              VRT(IRPA,1),2,IRPAI,LWIC28)
        CALL ASSYM3(IRPAI,VRT(1,1),IRPDPD(IRPCD,1),IRPDPD(IRPCD,13),
     1              VRT(IRPA,1),ICORE(IOFFV),ICORE(IOFFV1),
     1              IOFFVV,1)
        ELSE
        CALL GETLST(ICORE(IOFFV),
     1              IOFFVO(IRPI,IRPAI,1) + (I-1)*VRT(IRPA,1) + 1,
     1              VRT(IRPA,1),2,IRPAI,LWIC25)
        ENDIF
C
      CALL XGEMM('T','N',VRT(IRPA,1),VRT(IRPB,2),IRPDPD(IRPCD,1),
     1           -1.0D+00,
     1           ICORE(IOFFV),IRPDPD(IRPCD,1),
     1           T3(IADT3(IRPB)),IRPDPD(IRPCD,1),
     1            0.0D+00,
     1            ICORE(IADT2E(IRPB)),VRT(IRPA,1))
  820 CONTINUE
C
      JK = (K-1)*POP(IRPJ,1) + J
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPK,IRPJK,5)+JK,
     1            1,1,IRPJK,LIST2I3)
C
      CALL SYMTR3(IRPAB,VRT(1,1),VRT(1,2),IRPDPD(IRPAB,13),1,
     1            ICORE(IADT2E(1)),SCR1,SCR2,SCR3)
C
      KJ = (J-1)*POP(IRPK,2) + K
      CALL GETLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPJK,6)+KJ,
     1            1,1,IRPJK,LIST2I3)
      CALL   VADD(ICORE(IADT2I),ICORE(IADT2I),ICORE(IADT2E(1)),
     1            IRPDPD(IRPAB,13), 1.0D+00)
      CALL PUTLST(ICORE(IADT2I),IOFFOO(IRPJ,IRPJK,6)+KJ,
     1            1,1,IRPJK,LIST2I3)
      RETURN
      END
