      SUBROUTINE E_T2T314O(W,VIJ,VIK,VJK,ICORE,
     1                     IADW,
     1                     IRPI,IRPJ,IRPK,IRPIJ,IRPIK,IRPJK,
     1                     I,J,K,ISPIN,LNVOIJ,LNVOIK,LNVOJK,IRREPX)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION W(1),ICORE(1)
      DOUBLE PRECISION VIJ(LNVOIJ,1),VIK(LNVOIK,1),VJK(LNVOJK,1)
      INTEGER DIRPRD,POP,VRT
      DIMENSION IADW(8)
      DIMENSION IADV(8),LENV(8)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     &                NF1BB,NF2BB
      COMMON /T3OFF/  IOFFVV(8,8,10),IOFFOO(8,8,10),IOFFVO(8,8,4)
      COMMON /T2ILIS/ LIST2I1,LIST2I2,LIST2I3
      COMMON /LISWI/  LWIC11,LWIC12,LWIC13,LWIC14,
     &                LWIC15,LWIC16,LWIC17,LWIC18,
     &                LWIC21,LWIC22,LWIC23,LWIC24,
     &                LWIC25,LWIC26,LWIC27,LWIC28,
     &                LWIC31,LWIC32,LWIC33,
     &                LWIC34,LWIC35,LWIC36,
     &                LWIC37,LWIC38,LWIC39,LWIC40,LWIC41,LWIC42
C
      INDEX(I) = I*(I-1)/2
C
      IRREPT = IRREPX
      IRREPW = 1
      LIST2OFF = LIST2I1 - 1
      LWOFF    = LWIC21  - 1
C
      IF(ISPIN.EQ.1)THEN
      LIST2I = LIST2I1
      ELSE
      LIST2I = LIST2I2
      ENDIF
C
C     ROUTINE TO COMPUTE INCLUSION OF T3 AAA OR T3 BBB IN T2 AA 
C     OR T2 BB.
C
C     W IS (A<B,C) REPRESENTATION OF T3 (A<B<C).
C
C
C      AB  AB                      ABC
C     D   T    =  - SUM  <JK//MC> T       I<J<K   W(A<B,C) * V(C)
C      IM  IM       J<K            IJK
C                    C
C
      IRPMC = DIRPRD(IRREPW,IRPJK)
      IRPCM = IRPMC
      I000 = 1
      I010 = I000 + IRPDPD(IRPMC,8+ISPIN)
      I020 = I010 + IRPDPD(IRPMC,8+ISPIN)
      I030 = I020 + IRPDPD(IRPMC,8+ISPIN)
      I040 = I030 + IRPDPD(IRPMC,8+ISPIN)
C
      IF(IRPJ.EQ.IRPK)THEN
       JK = IOFFOO(IRPK,IRPJK,ISPIN) + INDEX(K-1) + J
      ELSE
       JK = IOFFOO(IRPK,IRPJK,ISPIN) + (K-1)*POP(IRPJ,ISPIN) + J
      ENDIF
      CALL GETLST(ICORE,JK,1,2,IRPJK,LWOFF+ISPIN)
      CALL SYMTR3(IRPMC,POP(1,ISPIN),VRT(1,ISPIN),
     &            IRPDPD(IRPMC,8+ISPIN),1,
     &            ICORE(I000),ICORE(I010),ICORE(I020),ICORE(I030))
C
C     Set addresses for integrals based on (c,m) ordering.
C
      DO   10 IRPM=1,NIRREP
      IRPC = DIRPRD(IRPM,IRPCM)
      LENV(IRPM) = VRT(IRPC,ISPIN)*POP(IRPM,ISPIN)
      IF(IRPM.EQ.1)THEN
      IADV(IRPM) = 1
      ELSE
      IADV(IRPM) = IADV(IRPM-1) + LENV(IRPM-1)
      ENDIF
   10 CONTINUE
C
C     Set address for T2.
C
      IOFFT2 = IADV(NIRREP) + LENV(NIRREP)
C
      DO   50 IRPM=1,NIRREP
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 50
C
      IRPIM = DIRPRD(IRPI,IRPM)
      IRPAB = DIRPRD(IRREPT,IRPIM)
      IF(IRPM.GT.IRPI)THEN
C
      DO   20 M=1,POP(IRPM,ISPIN)
      IM = IOFFOO(IRPM,IRPIM,ISPIN) + (M-1)*POP(IRPI,ISPIN) + I
      CALL GETLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
C
      IRPC = DIRPRD(IRPJK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
C    1            VJK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),JK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
   20 CONTINUE
      ENDIF
C
      IF(IRPM.LT.IRPI)THEN
C
      DO   30 M=1,POP(IRPM,ISPIN)
      IM = IOFFOO(IRPI,IRPIM,ISPIN) + (I-1)*POP(IRPM,ISPIN) + M
      CALL GETLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
C
      IRPC = DIRPRD(IRPJK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VJK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),JK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
   30 CONTINUE
      ENDIF
C
      IF(IRPM.EQ.IRPI)THEN
C
      DO   40 M=1,POP(IRPM,ISPIN)
C
      IF(M.GT.I)THEN
      IM = IOFFOO(IRPM,IRPIM,ISPIN) + INDEX(M-1) + I
      CALL GETLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
C
      IRPC = DIRPRD(IRPJK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VJK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),JK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
      ENDIF
C
      IF(M.LT.I)THEN
      IM = IOFFOO(IRPI,IRPIM,ISPIN) + INDEX(I-1) + M
      CALL GETLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
C
      IRPC = DIRPRD(IRPJK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VJK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),JK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),IM,1,1,IRPIM,LIST2I)
      ENDIF
   40 CONTINUE
      ENDIF
   50 CONTINUE
C
C      AB  AB                      ABC
C     D   T    =    SUM  <IK//MC> T       I<J<K   W(A<B,C) * V(C)
C      JM  JM       I<K            IJK
C                    C
      IRPMC = DIRPRD(IRREPW,IRPIK)
      IRPCM = IRPMC
      I000 = 1
      I010 = I000 + IRPDPD(IRPMC,8+ISPIN)
      I020 = I010 + IRPDPD(IRPMC,8+ISPIN)
      I030 = I020 + IRPDPD(IRPMC,8+ISPIN)
      I040 = I030 + IRPDPD(IRPMC,8+ISPIN)
C
      IF(IRPI.EQ.IRPK)THEN
       IK = IOFFOO(IRPK,IRPIK,ISPIN) + INDEX(K-1) + I
      ELSE
       IK = IOFFOO(IRPK,IRPIK,ISPIN) + (K-1)*POP(IRPI,ISPIN) + I
      ENDIF
      CALL GETLST(ICORE,IK,1,2,IRPIK,LWOFF+ISPIN)
      CALL SYMTR3(IRPMC,POP(1,ISPIN),VRT(1,ISPIN),
     &            IRPDPD(IRPMC,8+ISPIN),1,
     &            ICORE(I000),ICORE(I010),ICORE(I020),ICORE(I030))
C
      DO  110 IRPM=1,NIRREP
      IRPC = DIRPRD(IRPM,IRPCM)
      LENV(IRPM) = VRT(IRPC,ISPIN)*POP(IRPM,ISPIN)
      IF(IRPM.EQ.1)THEN
       IADV(IRPM) = 1
      ELSE
       IADV(IRPM) = IADV(IRPM-1) + LENV(IRPM-1)
      ENDIF
  110 CONTINUE
C
      IOFFT2 = IADV(NIRREP) + LENV(NIRREP)
C
      DO  150 IRPM=1,NIRREP
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 150
C
      IRPJM = DIRPRD(IRPJ,IRPM)
      IRPAB = DIRPRD(IRREPT,IRPJM)
      IF(IRPM.GT.IRPJ)THEN
C
      DO  120 M=1,POP(IRPM,ISPIN)
      JM = IOFFOO(IRPM,IRPJM,ISPIN) + (M-1)*POP(IRPJ,ISPIN) + J
      CALL GETLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
C
      IRPC = DIRPRD(IRPCM,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
  120 CONTINUE
      ENDIF
C
      IF(IRPM.LT.IRPJ)THEN
C
      DO  130 M=1,POP(IRPM,ISPIN)
      JM = IOFFOO(IRPJ,IRPJM,ISPIN) + (J-1)*POP(IRPM,ISPIN) + M
      CALL GETLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
C
      IRPC = DIRPRD(IRPIK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
  130 CONTINUE
      ENDIF
C
      IF(IRPM.EQ.IRPJ)THEN
C
      DO  140 M=1,POP(IRPM,ISPIN)
C
      IF(M.GT.J)THEN
      JM = IOFFOO(IRPM,IRPJM,ISPIN) + INDEX(M-1) + J
      CALL GETLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
C
      IRPC = DIRPRD(IRPIK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
      ENDIF
C
      IF(M.LT.J)THEN
      JM = IOFFOO(IRPJ,IRPJM,ISPIN) + INDEX(J-1) + M
      CALL GETLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
C
      IRPC = DIRPRD(IRPIK,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIK(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IK),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),JM,1,1,IRPJM,LIST2I)
      ENDIF
  140 CONTINUE
      ENDIF
  150 CONTINUE
C
C      AB  AB                      ABC
C     D   T    =  - SUM  <IJ//MC> T       I<J<K   W(A<B,C) * V(C)
C      KM  KM       I<J            IJK
C                    C
C
      IRPMC = DIRPRD(IRREPW,IRPIJ)
      IRPCM = IRPMC
      I000 = 1
      I010 = I000 + IRPDPD(IRPMC,8+ISPIN)
      I020 = I010 + IRPDPD(IRPMC,8+ISPIN)
      I030 = I020 + IRPDPD(IRPMC,8+ISPIN)
      I040 = I030 + IRPDPD(IRPMC,8+ISPIN)
C
      IF(IRPI.EQ.IRPJ)THEN
       IJ = IOFFOO(IRPJ,IRPIJ,ISPIN) + INDEX(J-1) + I
      ELSE
       IJ = IOFFOO(IRPJ,IRPIJ,ISPIN) + (J-1)*POP(IRPI,ISPIN) + I
      ENDIF
      CALL GETLST(ICORE,IJ,1,2,IRPIJ,LWOFF+ISPIN)
      CALL SYMTR3(IRPMC,POP(1,ISPIN),VRT(1,ISPIN),
     &            IRPDPD(IRPMC,8+ISPIN),1,
     &            ICORE(I000),ICORE(I010),ICORE(I020),ICORE(I030))
C
      DO  210 IRPM=1,NIRREP
      IRPC = DIRPRD(IRPM,IRPCM)
      LENV(IRPM) = VRT(IRPC,ISPIN)*POP(IRPM,ISPIN)
      IF(IRPM.EQ.1)THEN
       IADV(IRPM) = 1
      ELSE
       IADV(IRPM) = IADV(IRPM-1) + LENV(IRPM-1)
      ENDIF
  210 CONTINUE
C
      IOFFT2 = IADV(NIRREP) + LENV(NIRREP)
C
      IF(IRPI.EQ.IRPJ)THEN
      IJ = INDEX(J-1) + I
      ELSE
      IJ = (J-1)*POP(IRPI,ISPIN) + I
      ENDIF
C
      DO  250 IRPM=1,NIRREP
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 250
C
      IRPKM = DIRPRD(IRPK,IRPM)
      IRPAB = DIRPRD(IRREPT,IRPKM)
      IF(IRPM.GT.IRPK)THEN
C
      DO  220 M=1,POP(IRPM,ISPIN)
      KM = IOFFOO(IRPM,IRPKM,ISPIN) + (M-1)*POP(IRPK,ISPIN) + K
      CALL GETLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
C
      IRPC = DIRPRD(IRPIJ,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIJ(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IJ),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
  220 CONTINUE
      ENDIF
C
      IF(IRPM.LT.IRPK)THEN
C
      DO  230 M=1,POP(IRPM,ISPIN)
      KM = IOFFOO(IRPK,IRPKM,ISPIN) + (K-1)*POP(IRPM,ISPIN) + M
      CALL GETLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
C
      IRPC = DIRPRD(IRPIJ,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIJ(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IJ),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
  230 CONTINUE
      ENDIF
C
      IF(IRPM.EQ.IRPK)THEN
C
      DO  240 M=1,POP(IRPM,ISPIN)
C
      IF(M.GT.K)THEN
      KM = IOFFOO(IRPM,IRPKM,ISPIN) + INDEX(M-1) + K
      CALL GETLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
C
      IRPC = DIRPRD(IRPIJ,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIJ(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IJ),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,1)
C
      CALL PUTLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
      ENDIF
C
      IF(M.LT.K)THEN
      KM = IOFFOO(IRPK,IRPKM,ISPIN) + INDEX(K-1) + M
      CALL GETLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
C
      IRPC = DIRPRD(IRPIJ,IRPM)
      CALL MATVEC(W(IADW(IRPC)),
c    1            VIJ(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN),IJ),
     1            ICORE(IADV(IRPM) + (M-1)*VRT(IRPC,ISPIN)),
     1            ICORE(IOFFT2),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPC,ISPIN),0,0)
C
      CALL PUTLST(ICORE(IOFFT2),KM,1,1,IRPKM,LIST2I)
      ENDIF
  240 CONTINUE
      ENDIF
  250 CONTINUE
      RETURN
      END
