      SUBROUTINE FETCHVEC(IRREPX,SCR,IUHF,IOFFT1,LISTT1,LISTT2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SCR(*)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      IOFFC=1
      DO 12 ISPIN=1,1+IUHF
       LENSIN=IRPDPD(IRREPX,8+ISPIN)
       CALL GETLST(SCR(IOFFC),1,1,1,ISPIN+IOFFT1,LISTT1)
       IOFFC=IOFFC+LENSIN
12    CONTINUE
      DO 13 ISPIN=3,3-2*IUHF,-1
       LISTD=LISTT2+ISPIN
       ISIZE=IDSYMSZ(IRREPX,ISYTYP(1,LISTD),ISYTYP(2,LISTD))
       CALL GETALL(SCR(IOFFC),ISIZE,IRREPX,LISTD)
       IOFFC=IOFFC+ISIZE
13    CONTINUE
      RETURN
      END
