      SUBROUTINE GW5INUHF2(ICORE,MAXCOR,IUHF,IRREPT,LZOFF,LWOFF,LTOFF)
C
C THIS ROUTINE CALCULATES THE INITIAL T2*W CONTRIBUTION TO THE
C W5 HBAR INTERMEDIATES FOR SPIN CASE ABAB [LIST 30]
C
C W(Ab,Ci) = T(Mi,Eb)*<AM||CE> + T(im,be)*W<Ce|Am> - T(Mi,Ae)*<Ce|Mb>
C
CEND
cjdw  IMPLICIT INTEGER (A-Z)
      IMPLICIT NONE
C-----------------------------------------------------------------------
      INTEGER ICORE,MAXCOR,IUHF,IRREPT,LZOFF,LWOFF,LTOFF
      LOGICAL TERM1,TERM2
C-----------------------------------------------------------------------
      INTEGER IINTLN,IFLTLN,IINTFP,IALONE,IBITWD,
     &        POP,VRT,NT,NFEA,NFMI,IRPDPD,ISYTYP,ID,ISYMOFF,
     &        NSTART,NIRREP,IRREPY,DIRPRD
C-----------------------------------------------------------------------
      DOUBLE PRECISION ONE,ONEM,TWO,ZILCH,HALF
      INTEGER ILOCT,ILOCW,NDIMW,POPDUM
      INTEGER LISTZ,LISTW,LISTT,LST401,LSTSCR,IREC
      INTEGER I000,I010,I020,I030,ITMP1,ITMP2,ITMP3,IOFFZ,IOFFW,IOFFT
      INTEGER IRREP,IRREPA,IRREPAB,IRREPAE,IRREPAI,IRREPB,IRREPBI,
     &        IRREPC,IRREPCI,IRREPEM,IRREPI,IRREPM
      INTEGER NROW,NCOL,NSUM,NUMA,NUMB,NUMC,NUMI,I,C
      INTEGER TARSIZ,DISSYT,NUMDST,MAXT,NSIZET,INCREM,INCREM2
C-----------------------------------------------------------------------
      INTEGER IDSYMSZ
C-----------------------------------------------------------------------
      DIMENSION ICORE(MAXCOR),ILOCT(8),ILOCW(8,8),NDIMW(8)
      DIMENSION POPDUM(8)
C-----------------------------------------------------------------------
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFEA(2),NFMI(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYMLOC/ISYMOFF(8,8,25)
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
C
      DATA ONE,ONEM,ZILCH,TWO,HALF /1.0D0,-1.0D0,0.0D0,2.0D0,0.5D0/
C
C-----------------------------------------------------------------------
CJDW  Avoid 401 conflicts.
C-----------------------------------------------------------------------
      LST401 = 411
C
C DO CONTRACTION WITH AAAA INTEGRALS
C
      CALL NEWTYP2(1,LST401,19,9,.TRUE.)
cjdw  LISTZ=130+IOFFLIST
      LISTZ= LZOFF + 4
C
C BEGIN BY REORDERING W(C<E,AM) => W(AE,CM) ON DISK
C
cjdw  LISTW=27
      LISTW= LWOFF + 1
      LSTSCR=LST401
      CALL SYMTRLST(ICORE,MAXCOR,IUHF,
     &              VRT(1,1),VRT(1,1),VRT(1,1),POP(1,1),1,1,19,19,
     &              9,9,LISTW,LSTSCR,1,
     &             .FALSE.,.TRUE.,.FALSE.)
      CALL IZERO(POPDUM,8)
      POPDUM(1)=1
C
C CALCULATE SIZES OF W(AE,M) ARRAYS FOR EACH SYMMETRY OF C   
C AND OFFSETS INTO REORDERED W(EM,A) ARRAY
C
      DO 5 IRREPC=1,NIRREP
       NDIMW(IRREPC)=0
       INCREM2=0
       DO 6 IRREPM=1,NIRREP
        IRREPAE=DIRPRD(IRREPM,IRREPC)
        INCREM=POP(IRREPM,1)*IRPDPD(IRREPAE,19)
        ILOCW(IRREPM,IRREPC)=IINTFP*INCREM2
        INCREM2=VRT(IRREPM,1)*IRPDPD(IRREPAE,9)+INCREM2
        NDIMW(IRREPC)=NDIMW(IRREPC)+INCREM
6      CONTINUE
5     CONTINUE
C
C READ IN T VECTOR AS T(EM,bi)
C
cjdw  LISTT =37
      LISTT = LTOFF + 37
cjdw  NSIZET=ISYMSZ(ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      NSIZET=IDSYMSZ(IRREPT,ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      I000=1
      I010=I000+IINTFP*NSIZET
cjdw  CALL GETALL(ICORE(I000),NSIZET,1,LISTT)
      CALL GETALL(ICORE(I000),NSIZET,IRREPT,LISTT)
      IOFFT=1
      DO 7 IRREP=1,NIRREP
       ILOCT(IRREP)=IOFFT
cjdw   DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
       DISSYT=IRPDPD(DIRPRD(IRREPT,IRREP),ISYTYP(1,LISTT))
       NUMDST=IRPDPD(IRREP,ISYTYP(2,LISTT))
       IOFFT=IOFFT+IINTFP*NUMDST*DISSYT 
7     CONTINUE
C      
C FIRST TERM:
C
C   Z(Ab,Ci) <= T(Mi,Eb)*<CE||AM>
C
C INTEGRALS STORED NOW AS W(AE,CM)
C T VECTOR HELD IN CORE AS T(EM,bi)
C
C LOOP OVER IRREPS OF TARGET
C
      DO 10 IRREPCI=1,NIRREP
cjdw
       IRREPAB = DIRPRD(IRREPT,IRREPCI)
cjdw   TARSIZ=IRPDPD(IRREPCI,13)
       TARSIZ=IRPDPD(IRREPAB,13)
       DO 11 IRREPI=1,NIRREP
        IRREPC=DIRPRD(IRREPI,IRREPCI)
        NUMI=POP(IRREPI,2)
        NUMC=VRT(IRREPC,1)
cjdw    I020=I010+IINTFP*NDIMW(IRREPC)
cjdw    I030=I020+IINTFP*NDIMW(IRREPC)
        I020=I010+IINTFP*MAX(NDIMW(IRREPC),TARSIZ)
        I030=I020+IINTFP*MAX(NDIMW(IRREPC),TARSIZ)
        DO 12 C=1,NUMC
C
C READ IN ALL W(AE;M) FOR THIS VALUE OF C
C
         CALL GET3(ICORE(I020),LSTSCR,1,C,IRREPC,
     &             VRT(1,1),VRT(1,1),VRT(1,1),POP(1,1),19,9,'124',
     &             .FALSE.,.FALSE.,ICORE(I020))
C
C REORDER TO W(EM;A)
C
         CALL SSTGEN(ICORE(I020),ICORE(I010),NDIMW(IRREPC),
     &               VRT(1,1),VRT(1,1),POP(1,1),
     &               POPDUM,ICORE(I030),IRREPC,'2314')
C
         DO 13 I=1,NUMI
          DO 14 IRREPB=1,NIRREP
           IRREPBI=DIRPRD(IRREPB,IRREPI)
cjdw       IRREPEM=IRREPBI
           IRREPEM=DIRPRD(IRREPT,IRREPBI)
cjdw       IRREPA=DIRPRD(IRREPB,IRREPCI)
           IRREPA=DIRPRD(IRREPB,IRREPAB)
           NUMB=VRT(IRREPB,2)
           NUMA=VRT(IRREPA,1)
           NROW=NUMA
           NCOL=NUMB
           NSUM=IRPDPD(IRREPEM,9)
cjdw       IOFFT=ILOCT(IRREPEM)+IINTFP*
cjdw &           (NSUM*(ISYMOFF(IRREPI,IRREPEM,10)-1)+
cjdw &           NSUM*NUMB*(I-1))
           IOFFT=ILOCT(IRREPBI)+IINTFP*
     &           (NSUM*(ISYMOFF(IRREPI,IRREPBI,10)-1)+
     &           NSUM*NUMB*(I-1))
           IOFFW=I010+ILOCW(IRREPA,IRREPC)
cjdw       IOFFZ=I020+IINTFP*(ISYMOFF(IRREPB,IRREPCI,13)-1)
           IOFFZ=I020+IINTFP*(ISYMOFF(IRREPB,IRREPAB,13)-1)
C
C FORM Z(Ab) = W(EM,A) * T(EM,bi) FOR FIXED i
C
           CALL XGEMM('T','N',NROW,NCOL,NSUM,ONEM,ICORE(IOFFW),NSUM,
     &                ICORE(IOFFT),NSUM,ZILCH,ICORE(IOFFZ),NUMA)
14        CONTINUE
C
C CALCULATE ADDRESS OF Ci RECORD
C          
          IREC=C+NUMC*(I-1)+ISYMOFF(IRREPI,IRREPCI,11)-1
cjdw 3 lines
          CALL GETLST(ICORE(I030),IREC,1,1,IRREPCI,LISTZ)
          CALL SAXPY (IRPDPD(IRREPAB,13),ONEM,ICORE(I020),1,
     &                ICORE(I030),1)
C
cjdw      CALL PUTLST(ICORE(I020),IREC,1,1,IRREPCI,LISTZ)
          CALL PUTLST(ICORE(I030),IREC,1,1,IRREPCI,LISTZ)
13       CONTINUE
12      CONTINUE
11     CONTINUE
10    CONTINUE
C
C NOW DO CONTRIBUTION FROM LIST 30 INTEGRALS
C
cjdw  LISTW=30
      LISTW= LWOFF + 4
      CALL NEWTYP2(1,LST401,13,11,.TRUE.)
C
C BEGIN BY REORDERING W(Ce,Am) => W(Ae,Cm)
C
      CALL SYMTRLST(ICORE,MAXCOR,IUHF,
     &              VRT(1,1),VRT(1,2),VRT(1,1),POP(1,2),
     &              1,13,13,13,11,11,LISTW,LSTSCR,1,
     &              .FALSE.,.FALSE.,.FALSE.)
      CALL IZERO(POPDUM,8)
      POPDUM(1)=1
C
C CALCULATE SIZES OF W(Ae,m) ARRAYS FOR EACH SYMMETRY OF C   
C AND OFFSETS INTO REORDERED W(em,A) ARRAY
C
      DO 105 IRREPC=1,NIRREP
       NDIMW(IRREPC)=0
       INCREM2=0
       DO 106 IRREPM=1,NIRREP
        IRREPAE=DIRPRD(IRREPM,IRREPC)
        INCREM=POP(IRREPM,2)*IRPDPD(IRREPAE,13)
        ILOCW(IRREPM,IRREPC)=IINTFP*INCREM2
        INCREM2=VRT(IRREPM,1)*IRPDPD(IRREPAE,10)+INCREM2
        NDIMW(IRREPC)=NDIMW(IRREPC)+INCREM
106    CONTINUE
105   CONTINUE
C
C READ IN T VECTOR AS T(em,bi)
C
cjdw  LISTT =35
      LISTT = LTOFF + 35
cjdw  NSIZET=ISYMSZ(ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      NSIZET=IDSYMSZ(IRREPT,ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      I000=1
      I010=I000+IINTFP*NSIZET
cjdw  CALL GETALL(ICORE(I000),NSIZET,1,LISTT)
      CALL GETALL(ICORE(I000),NSIZET,IRREPT,LISTT)
      IOFFT=1
      DO 107 IRREP=1,NIRREP
       ILOCT(IRREP)=IOFFT
cjdw   DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
       DISSYT=IRPDPD(DIRPRD(IRREPT,IRREP),ISYTYP(1,LISTT))
       NUMDST=IRPDPD(IRREP,ISYTYP(2,LISTT))
       IOFFT=IOFFT+IINTFP*NUMDST*DISSYT 
107   CONTINUE
C     
C SECOND TERM:
C
C   Z(Ab,Ci) <= T(im,be)*<Ce|Am>
C
C INTEGRALS STORED NOW AS W(Ae,Cm)
C T VECTOR HELD IN CORE AS T(em,bi)
C
C LOOP OVER IRREPS OF TARGET
C
      DO 110 IRREPCI=1,NIRREP
cjdw
       IRREPAB = DIRPRD(IRREPT,IRREPCI)
cjdw   TARSIZ=IRPDPD(IRREPCI,13)
       TARSIZ=IRPDPD(IRREPAB,13)
       DO 111 IRREPI=1,NIRREP
        IRREPC=DIRPRD(IRREPI,IRREPCI)
        NUMI=POP(IRREPI,2)
        NUMC=VRT(IRREPC,1)
cjdw    I020=I010+IINTFP*NDIMW(IRREPC)
cjdw    I030=I020+IINTFP*NDIMW(IRREPC)
        I020=I010+IINTFP*MAX(NDIMW(IRREPC),TARSIZ)
        I030=I020+IINTFP*MAX(NDIMW(IRREPC),TARSIZ)
        DO 112 C=1,NUMC
C
C READ IN ALL W(Ae;m) FOR THIS VALUE OF C
C
         CALL GET3(ICORE(I020),LSTSCR,1,C,IRREPC,
     &             VRT(1,1),VRT(1,2),VRT(1,1),
     &             POP(1,2),13,11,'124',
     &             .FALSE.,.FALSE.,ICORE(I020))
C
C REORDER TO W(em;A)
C
         CALL SSTGEN(ICORE(I020),ICORE(I010),NDIMW(IRREPC),
     &               VRT(1,1),VRT(1,2),POP(1,2),
     &               POPDUM,ICORE(I030),IRREPC,'2314')
C
         DO 113 I=1,NUMI
          DO 114 IRREPB=1,NIRREP
           IRREPBI=DIRPRD(IRREPB,IRREPI)
cjdw       IRREPEM=IRREPBI
           IRREPEM=DIRPRD(IRREPT,IRREPBI)
cjdw       IRREPA=DIRPRD(IRREPB,IRREPCI)
           IRREPA=DIRPRD(IRREPB,IRREPAB)
           NUMB=VRT(IRREPB,2)
           NUMA=VRT(IRREPA,1)
           NROW=NUMA
           NCOL=NUMB
           NSUM=IRPDPD(IRREPEM,10)
cjdw       IOFFT=ILOCT(IRREPEM)+IINTFP*
cjdw &           (NSUM*(ISYMOFF(IRREPI,IRREPEM,10)-1)+
cjdw &           NSUM*NUMB*(I-1))
           IOFFT=ILOCT(IRREPBI)+IINTFP*
     &           (NSUM*(ISYMOFF(IRREPI,IRREPBI,10)-1)+
     &           NSUM*NUMB*(I-1))
           IOFFW=I010+ILOCW(IRREPA,IRREPC)
cjdw       IOFFZ=I020+IINTFP*(ISYMOFF(IRREPB,IRREPCI,13)-1)
           IOFFZ=I020+IINTFP*(ISYMOFF(IRREPB,IRREPAB,13)-1)
C
C FORM Z(Ab) = W(em,A) * T(em,bi) FOR FIXED i
C
           CALL XGEMM('T','N',NROW,NCOL,NSUM,ONE,ICORE(IOFFW),NSUM,
     &                ICORE(IOFFT),NSUM,ZILCH,ICORE(IOFFZ),NUMA)
114       CONTINUE
C
C CALCULATE ADDRESS OF CI RECORD
C          
          IREC=C+NUMC*(I-1)+ISYMOFF(IRREPI,IRREPCI,11)-1
          CALL GETLST(ICORE(I030),IREC,1,1,IRREPCI,LISTZ)
cjdw      CALL SAXPY (IRPDPD(IRREPCI,13),ONE,ICORE(I030),1,
cjdw &                ICORE(I020),1)
          CALL SAXPY (IRPDPD(IRREPAB,13),ONEM,ICORE(I020),1,
     &                ICORE(I030),1)
cjdw      CALL PUTLST(ICORE(I020),IREC,1,1,IRREPCI,LISTZ)
          CALL PUTLST(ICORE(I030),IREC,1,1,IRREPCI,LISTZ)
113      CONTINUE
112     CONTINUE
111    CONTINUE
110   CONTINUE
C
C NOW DO CONTRIBUTION FROM LIST 29 INTEGRALS
C
cjdw  LISTW=29
      LISTW= LWOFF + 3
      CALL NEWTYP2(1,LST401,18,13,.TRUE.)
C
C BEGIN BY REORDERING W(Ce,Mb) => W(Me,Cb)
C
      CALL SYMTRLST(ICORE,MAXCOR,IUHF,
     &              VRT(1,1),VRT(1,2),POP(1,1),VRT(1,2),
     &              1,13,18,18,18,13,LISTW,LSTSCR,1,
     &              .FALSE.,.FALSE.,.FALSE.)
      CALL IZERO(POPDUM,8)
      POPDUM(1)=1
C
C CALCULATE SIZES OF W(Me,b) ARRAYS FOR EACH SYMMETRY OF C   
C AND OFFSETS INTO REORDERED W(Me,b) ARRAY
C
      DO 205 IRREPC=1,NIRREP
       NDIMW(IRREPC)=0
       INCREM2=0
       DO 206 IRREPM=1,NIRREP
        IRREPAE=DIRPRD(IRREPM,IRREPC)
        INCREM=VRT(IRREPM,2)*IRPDPD(IRREPAE,18)
        ILOCW(IRREPM,IRREPC)=IINTFP*INCREM2
        INCREM2=VRT(IRREPM,2)*IRPDPD(IRREPAE,18)+INCREM2
        NDIMW(IRREPC)=NDIMW(IRREPC)+INCREM
206    CONTINUE
205   CONTINUE
C
C READ IN T VECTOR AS T(eM,Ai) AND TRANSPOSE BRA INDICES
C
cjdw  LISTT =38
      LISTT = LTOFF + 38
cjdw  NSIZET=ISYMSZ(ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      NSIZET=IDSYMSZ(IRREPT,ISYTYP(1,LISTT),ISYTYP(2,LISTT))
      I000=1
      I010=I000+IINTFP*NSIZET
cjdw  CALL GETALL(ICORE(I000),NSIZET,1,LISTT)
      CALL GETALL(ICORE(I000),NSIZET,IRREPT,LISTT)
      IOFFT=1
      DO 207 IRREP=1,NIRREP
       ILOCT(IRREP)=IOFFT
cjdw   DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
       DISSYT=IRPDPD(DIRPRD(IRREPT,IRREP),ISYTYP(1,LISTT))
       NUMDST=IRPDPD(IRREP,ISYTYP(2,LISTT))
       MAXT=MAX(DISSYT,NUMDST)
       ITMP1=I010
       ITMP2=ITMP1+IINTFP*MAXT
       ITMP3=ITMP2+IINTFP*MAXT
cjdw   CALL SYMTR3(IRREP,VRT(1,2),POP(1,1),DISSYT,NUMDST,ICORE(IOFFT),
cjdw  &             ICORE(ITMP1),ICORE(ITMP2),ICORE(ITMP3))
       CALL SYMTR3(DIRPRD(IRREPT,IRREP),VRT(1,2),POP(1,1),DISSYT,NUMDST,
     &             ICORE(IOFFT),ICORE(ITMP1),ICORE(ITMP2),ICORE(ITMP3))
       IOFFT=IOFFT+IINTFP*NUMDST*DISSYT 
207   CONTINUE
C     
C SECOND TERM:
C
C   Z(Ab,Ci) <= T(Mi,Ae)*<Ce|Mb>
C
C INTEGRALS STORED NOW AS W(Me,Cb)
C T VECTOR HELD IN CORE AS T(Me,Ai)
C
C LOOP OVER IRREPS OF TARGET
C
      DO 210 IRREPCI=1,NIRREP
cjdw
       IRREPAB = DIRPRD(IRREPT,IRREPCI)
cjdw   TARSIZ=IRPDPD(IRREPCI,13)
       TARSIZ=IRPDPD(IRREPAB,13)
       DO 211 IRREPI=1,NIRREP
        IRREPC=DIRPRD(IRREPI,IRREPCI)
        NUMI=POP(IRREPI,2)
        NUMC=VRT(IRREPC,1)
        I020=I010+IINTFP*NDIMW(IRREPC)
        I030=I020+IINTFP*MAX(TARSIZ,NDIMW(IRREPC))
        DO 212 C=1,NUMC
C
C READ IN ALL W(Me,b) FOR THIS VALUE OF C
C
         CALL GET3(ICORE(I010),LSTSCR,1,C,IRREPC,
     &             POP(1,1),VRT(1,2),VRT(1,1),
     &             VRT(1,2),18,13,'124',
     &             .FALSE.,.FALSE.,ICORE(I010))
C
         DO 213 I=1,NUMI
          DO 214 IRREPB=1,NIRREP
           IRREPBI=DIRPRD(IRREPB,IRREPI)
cjdw       IRREPA=DIRPRD(IRREPB,IRREPCI)
           IRREPA=DIRPRD(IRREPB,IRREPAB)
           IRREPAI=DIRPRD(IRREPA,IRREPI)
cjdw       IRREPEM=IRREPAI
           IRREPEM=DIRPRD(IRREPT,IRREPAI)
           NUMB=VRT(IRREPB,2)
           NUMA=VRT(IRREPA,1)
           NROW=NUMB
           NCOL=NUMA
           NSUM=IRPDPD(IRREPEM,18)
cjdw       IOFFT=ILOCT(IRREPEM)+IINTFP*
cjdw &           (NSUM*(ISYMOFF(IRREPI,IRREPEM,11)-1)+
cjdw &           NSUM*NUMA*(I-1))
           IOFFT=ILOCT(IRREPAI)+IINTFP*
     &           (NSUM*(ISYMOFF(IRREPI,IRREPAI,11)-1)+
     &           NSUM*NUMA*(I-1))
           IOFFW=I010+ILOCW(IRREPB,IRREPC)
cjdw       IOFFZ=I020+IINTFP*(ISYMOFF(IRREPA,IRREPCI,23)-1)
           IOFFZ=I020+IINTFP*(ISYMOFF(IRREPA,IRREPAB,23)-1)
C
C FORM Z(bA) = W(eM,b) * T(eM,Ai)
C
           CALL XGEMM('T','N',NROW,NCOL,NSUM,ONE,ICORE(IOFFW),NSUM,
     &                ICORE(IOFFT),NSUM,ZILCH,ICORE(IOFFZ),NUMB)
214       CONTINUE
C
C CALCULATE ADDRESS OF CI RECORD
C          
          IREC=C+NUMC*(I-1)+ISYMOFF(IRREPI,IRREPCI,11)-1
cjdw      CALL SYMTRA(IRREPCI,VRT(1,2),VRT(1,1),1,ICORE(I020),
cjdw &                ICORE(I030))
          CALL SYMTRA(IRREPAB,VRT(1,2),VRT(1,1),1,ICORE(I020),
     &                ICORE(I030))
          CALL GETLST(ICORE(I020),IREC,1,1,IRREPCI,LISTZ)
cjdw      CALL SAXPY (IRPDPD(IRREPCI,13),ONE,ICORE(I030),1,
cjdw &                ICORE(I020),1)
          CALL SAXPY (IRPDPD(IRREPAB,13),ONEM,ICORE(I030),1,
     &                ICORE(I020),1)
cjdw      CALL PUTLST(ICORE(I020),IREC,1,1,IRREPCI,LISTZ)
          CALL PUTLST(ICORE(I020),IREC,1,1,IRREPCI,LISTZ)
213      CONTINUE
212     CONTINUE
211    CONTINUE
210   CONTINUE
C
C NOW ADD LISTS 30 AND 130
C
cjdw      DO 2000 IRREP=1,NIRREP
cjdw       LISTW=30
cjdw       LISTZ=130+IOFFLIST
cjdw       I000=1
cjdw       DISSIZ=IRPDPD(IRREP,ISYTYP(1,LISTW))
cjdw       NUMDIS=IRPDPD(IRREP,ISYTYP(2,LISTW))
cjdw       IF(DISSIZ.NE.0)THEN
cjdw        NINCOR=MAXCOR/(DISSIZ*IINTFP)
cjdw       ELSE
cjdw        NINCOR=2*NUMDIS
cjdw       ENDIF
cjdw       NBUNCH=MIN(NINCOR/2,NUMDIS)
cjdw       I010=I000+IINTFP*DISSIZ*NBUNCH
cjdw       ISTART=1
cjdw       NLEFT=NUMDIS
cjdw1      NREAD=MIN(NLEFT,NBUNCH)
cjdw       IF(TERM1)THEN
cjdw        CALL GETLST(ICORE(I000),ISTART,NREAD,1,IRREP,LISTW)
cjdw       ELSE
cjdw        CALL ZERO  (ICORE(I000),NREAD*DISSIZ)
cjdw       ENDIF
cjdw       IF(TERM2)THEN
cjdw        CALL GETLST(ICORE(I010),ISTART,NREAD,1,IRREP,LISTZ)
cjdw       ELSE
cjdw        CALL ZERO  (ICORE(I010),NREAD*DISSIZ)
cjdw       ENDIF
cjdw       CALL SAXPY (NREAD*DISSIZ,ONEM,ICORE(I010),1,ICORE(I000),1)
cjdw       CALL PUTLST(ICORE(I000),ISTART,NREAD,1,IRREP,LISTZ)
cjdw       NLEFT=NLEFT-NREAD
cjdw       ISTART=ISTART+NREAD
cjdw       IF(NLEFT.NE.0)GOTO 1
cjdw2000  CONTINUE
C
      RETURN
      END
