      SUBROUTINE LNORM(IRREPX,ROOT,SCR,MAXCOR,IUHF,X,C0)
C
C THIS ROUTINE DETERMINES THE APPROPRIATE NORMALIZATION FACTOR FOR
C THE LEFT EIGENSTATE.  THIS VALUE IS RETURNED AS VARIABLE "X"
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SCR(MAXCOR)
      COMMON/EXTRAP/MAXEXP,NREDUCE,NTOL,NSIZEC
C
      DATA ONE /1.0D0/
C
      I000=1
      I010=I000+NSIZEC
      I020=I010+NSIZEC
      I030=I020+NSIZEC
C
C READ IN LEFT AND RIGHT-HANDED VECTORS [passed in at bottom of scr]
C
      CALL GETLST(SCR(I000),2,1,1,1,472)
C
C NORMALIZE RIGHT VECTOR, ACCOUNTING PROPERLY FOR C0
C
      IF(IRREPX.EQ.1)THEN
       CALL CALCC0(IRREPX,ROOT,SCR(I000),SCR(I010),MAXCOR-I010+1,IUHF,
     &             C0)
       Z=ONE+C0*C0
       FACT=DSQRT(ONE/Z)
       CALL SSCAL (NSIZEC,FACT,SCR(I000),1)
       C0=C0*FACT
      ENDIF
      CALL PUTLST(SCR(I000),2,1,1,1,472)
      CALL SCOPY  (NSIZEC,SCR(I000),1,SCR(I020),1)
      IF(IUHF.EQ.0)THEN
       CALL SPNTSING(IRREPX,SCR(I020),SCR(I030),MAXCOR-I020+1)
      ENDIF
C      
      CALL GETLST(SCR(I010),3,1,1,1,472)

C
C RENORMALIZE LEFT VECTOR SUCH THAT <L|R>=1
C
      X=ONE/(SDOT(NSIZEC,SCR(I020),1,SCR(I010),1))
C
      RETURN
      END
