      SUBROUTINE NEW2324(ICORE,EVAL,MAXCOR,IUHF,IGETEVAL)
C
C THIS ROUTINE RESTORES LISTS 23 AND 24 TO THEIR ORIGINAL
C FORM AND IS REQUIRED ONLY FOR UHF-BASED CIS AND CISD CALCULATIONS
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION EVAL,ONE
      DIMENSION ICORE(MAXCOR),EVAL(*)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NJUNK(6)
C
      DATA ONE /1.0D0/
C
      NBAS=NOCCO(1)+NVRTO(1)
      IF(IGETEVAL.NE.0)THEN
       CALL GETREC(20,'JOBARC','SCFEVALA',IINTFP*NBAS,EVAL)
       CALL GETREC(20,'JOBARC','SCFEVALB',IINTFP*NBAS,
     &             EVAL(1+NBAS))
      ENDIF
      DO 10 ISPIN=1,2
       LISTW=22+ISPIN
       DO 20 IRREP=1,NIRREP
        DISSIZ=IRPDPD(IRREP,ISYTYP(1,LISTW))
        NUMDIS=IRPDPD(IRREP,ISYTYP(2,LISTW))
        I000=1
        I010=I000+IINTFP*NUMDIS*DISSIZ
        CALL GETLST(ICORE(I000),1,NUMDIS,1,IRREP,LISTW)
        CALL GETDELE(IRREP,1,ICORE(I010),EVAL(1+(ISPIN-1)*NBAS),
     &               POP(1,ISPIN),VRT(1,ISPIN),NOCCO(ISPIN))
        CALL SAXPY (NUMDIS,ONE,ICORE(I010),1,ICORE(I000),NUMDIS+1)
        CALL VMINUS(ICORE(I000),NUMDIS*DISSIZ)
        CALL PUTLST(ICORE(I000),1,NUMDIS,1,IRREP,LISTW)
20     CONTINUE
10    CONTINUE
C
      RETURN
      END
