
      SUBROUTINE NUCDIP(SCR)
C
C COMPUTE NUCLEAR CONTRIBUTION TO THE DIPOLE MOMENT AND
C WRITE IT TO JOBARC
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SCR(*),ISCR(150),D(3)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      IONE=1
      ITHR=3
      CALL GETREC(20,'JOBARC','NATOMS  ',IONE,NATOM)
      I000=1
      I010=I000+3*NATOM
      CALL GETREC(20,'JOBARC','COORD   ',3*NATOM*IINTFP,SCR)
      CALL GETREC(20,'JOBARC','ATOMCHRG',NATOM,ISCR)
C
      DO 5 I=1,NATOM
       SCR(I010-1+I)=DFLOAT(ISCR(I))
5     CONTINUE
C
      DO 10 IXYZ=1,3
       D(IXYZ)=SDOT(NATOM,SCR(I000-1+IXYZ),3,SCR(I010),1)
10    CONTINUE
C
      CALL PUTREC(20,'JOBARC','NUCDIPOL',ITHR*IINTFP,D)
C
      RETURN
      END
