      SUBROUTINE QUIKAA(ICORE,MAXCOR)
C
C THIS SUBROUTINE FORMS THE ALL ALPHA G(IAJB) INTERMEDIATE
C  FROM THE ABAB AND ABBA PIECES FOR RHF REFERENCE FUNCTIONS.
C
CEND
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER TOTSIZ
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      DATA ONEM /-1.0/
      TOTSIZ=ISYMSZ(ISYTYP(1,23),ISYTYP(1,23))
      I000=1
      I010=I000+TOTSIZ*IINTFP
      I020=I010+TOTSIZ*IINTFP 
      IF(I020.GT.MAXCOR)CALL INSMEM('QUIKAA',I020,MAXCOR)
      CALL GETALL(ICORE(I000),TOTSIZ,1,125)
      CALL GETALL(ICORE(I010),TOTSIZ,1,118)
      CALL SAXPY(TOTSIZ,ONEM,ICORE(I010),1,ICORE(I000),1)
      CALL PUTALL(ICORE,TOTSIZ,1,123)
      RETURN
      END
