      SUBROUTINE QUIKAA3(ICORE,MAXCOR,IRREPX,LISTOFF)
C
C THIS SUBROUTINE FORMS THE ALL ALPHA H(MEJB) INTERMEDIATE
C  FROM THE ABAB AND ABBA PIECES FOR RHF REFERENCE FUNCTIONS.
C
CEND
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER TOTSIZ
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      DATA ONEM /-1.0D0/
      TOTSIZ=IDSYMSZ(IRREPX,ISYTYP(1,23),ISYTYP(1,23))
      I000=1
      I010=I000+TOTSIZ*IINTFP
      I020=I010+TOTSIZ*IINTFP 
      IF(I020.GT.MAXCOR)CALL INSMEM('QUIKAA3',I020,MAXCOR)
      CALL GETALL(ICORE(I000),TOTSIZ,IRREPX,LISTOFF+4)
      CALL GETALL(ICORE(I010),TOTSIZ,IRREPX,LISTOFF+2)
      CALL SAXPY(TOTSIZ,ONEM,ICORE(I010),1,ICORE(I000),1)
      CALL PUTALL(ICORE,TOTSIZ,IRREPX,LISTOFF)
      RETURN
      END
