      SUBROUTINE R1L1Y2(ICORE,MAXCOR,IUHF)
C
C DRIVER FOR CALCULATING CONTRIBUTIONS OF R1 AND L1 VECTORS
C TO THE Y2 INTERMEDIATE.
C  
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR),I0R(2),I0L(2)
      COMMON/STATSYM/IRREPX
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      I0R(1)=1
      CALL GETLST(ICORE(I0R(1)),1,1,1,3,490)
      IF(IUHF.NE.0)THEN
       I0R(2)=I0R(1)+IINTFP*IRPDPD(IRREPX,9)
       CALL GETLST(ICORE(I0R(2)),1,1,1,4,490)
      ELSE
       I0R(2)=I0R(1)
      ENDIF 
      I0L(1)=I0R(2)+IINTFP*IRPDPD(IRREPX,10)
      CALL GETLST(ICORE(I0L(1)),1,1,1,1,490)
      IF(IUHF.NE.0)THEN
       I0L(2)=I0L(1)+IINTFP*IRPDPD(IRREPX,9)
       CALL GETLST(ICORE(I0L(2)),1,1,1,2,490)
      ELSE
       I0L(2)=I0L(1)
      ENDIF 
      I000=I0L(2)+IINTFP*IRPDPD(IRREPX,10)
      MXCOR=MAXCOR-I000+1
C
C INITIALIZE INTERMEDIATE WITH W(AB,IJ)
C
      DO 10 ISPIN=3,3-2*IUHF,-1
       LISTW=13+ISPIN
       LISTY=60+ISPIN
       ISIZE=ISYMSZ(ISYTYP(1,LISTW),ISYTYP(2,LISTW))
       IEND=I000+ISIZE*IINTFP
       IF(IEND.GE.MAXCOR) CALL INSMEM('R1L1Y2',IEND,MAXCOR)
       CALL GETALL (ICORE(I000),ISIZE,1,LISTW)
       CALL PUTALL (ICORE(I000),ISIZE,1,LISTY)
10    CONTINUE
C
C CALCULATE CONTRACTIONS
C
      CALL R1L1Y2A(ICORE(I0R(1)),ICORE(I0L(1)),ICORE(I000),MXCOR,IUHF)
      CALL R1L1Y2B(ICORE(I0R(1)),ICORE(I0L(1)),ICORE(I000),MXCOR,IUHF)
      CALL R1L1Y2C(ICORE(I0R(1)),ICORE(I0L(1)),ICORE(I000),MXCOR,IUHF)
C
      RETURN
      END
