      SUBROUTINE R1L2Y2L(F1,R1,ICORE,MAXCOR,IUHF)
C
C Y1(ab,ij) = F(me)*R(me) * L(ab,ij)
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ZILCH,TWO,SDOT,FACT,F1,R1
      DIMENSION ICORE(MAXCOR),R1(*),F1(*)
      COMMON/STATSYM/IRREPX
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA TWO,ZILCH/2.0D0,0.0D0/
C
      IF(IRREPX.NE.1)RETURN
C
      IOFF=1
      FACT=ZILCH
      DO 10 ISPIN=1,1+IUHF
       LENGTH=NT(ISPIN)
       FACT=FACT+SDOT(LENGTH,F1(IOFF),1,R1(IOFF),1)
       IOFF=IOFF+LENGTH
10    CONTINUE  
C
      IF(IUHF.EQ.0)FACT=FACT*TWO
C
      DO 20 ISPIN=3,3-2*IUHF,-1
       LISTZ=60+ISPIN
       LISTL=443+ISPIN
       ISIZE=ISYMSZ(ISYTYP(1,LISTZ),ISYTYP(2,LISTZ))
       I000=1
       I010=I000+IINTFP*ISIZE
       I020=I010+IINTFP*ISIZE
       CALL GETALL(ICORE(I000),ISIZE,1,LISTL)
       CALL GETALL(ICORE(I010),ISIZE,1,LISTZ)
       CALL SAXPY (ISIZE,FACT,ICORE(I000),1,ICORE(I010),1)
       CALL PUTALL(ICORE(I010),ISIZE,1,LISTZ)
20    CONTINUE
C
      RETURN
      END
