      SUBROUTINE R2L1Y1C(XI1,L1,ICORE,MAXCOR,IUHF)
C
C XI1(ai) = -1/2 L(an)*R(mn,ef)*W(mi,ef)
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM
      DIMENSION ICORE(MAXCOR),XI1(*),L1(*)
      COMMON/STATSYM/IRREPX
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMLOC/ISYMOFF(8,8,25)
C
      DATA ONE,ONEM/1.0D0,-1.0D0/
C
      IOFFXI=1
      IOFFL0=1
      DO 10 ISPIN=1,1+IUHF
       I0G=1
       I000=I0G+IINTFP*IRPDPD(IRREPX,20+ISPIN)
C
C FIRST PICK UP G(in) FROM LIST 491
C
       CALL GETLST(ICORE(I0G),1,1,1,ISPIN,491)
C
C FORM PRODUCT XI1(ai) = -L(an)*G(in)
C
       DO 11 IRREPI=1,NIRREP
        IRREPA=IRREPI
        IRREPN=DIRPRD(IRREPI,IRREPX)
        NUMA=VRT(IRREPA,ISPIN)
        NUMN=POP(IRREPN,ISPIN)
        NUMI=POP(IRREPI,ISPIN)
        IOFFL=IOFFL0+(ISYMOFF(IRREPN,IRREPX,8+ISPIN)-1)*IINTFP
        IOFFG=I0G+(ISYMOFF(IRREPN,IRREPX,20+ISPIN)-1)*IINTFP
        CALL XGEMM('N','T',NUMA,NUMI,NUMN,ONEM,L1(IOFFL),NUMA,
     &             ICORE(IOFFG),NUMI,ONE,XI1(IOFFXI),NUMA)
        IOFFXI=IOFFXI+IINTFP*NUMA*NUMI
11     CONTINUE
       IOFFL0=IOFFL0+IINTFP*IRPDPD(IRREPX,8+ISPIN)
C
10    CONTINUE
C
      RETURN
      END
