      SUBROUTINE R2L2RNGD(ICORE,MAXCOR,IUHF,R0,SORT)
C
C   THIS ROUTINE CALCULATES THE FOLLOWING INTERMEDIATE 
C
C   H(ME,IA) = - SUM N,F  L(MN,EF) [R(NI,FA) + R0 T(NI,FA)]
C
C  THIS TERM IS VERY SIMILAR TO THE T1(IJ,AB) CONTRIBUTION TO
C  THE W-RING INTERMEDIATE
C
C  THE SPIN CASES ARE
C
C    AAAA : =  - SUM M,E L(IM,BE) R(MJ,EA) - SUM m,e L(Im,Be) R(Jm,Ae)
C
C    ABAB : =  - SUM m,E L(Im,Eb) R(Jm,Ea)
C
C    ABBA : =  - SUM M,E L(IM,BE) R(Mj,Ea) - SUM m,e L(Im,Be) R(mj,eb)
C
C FOR UHF IN ADDITION THE BBBB BABA AND BABA SPIN CASES HAS TO CALCULATES
C
C
C  AAAA : LIST 54  (CALCULATED FROM ABAB AND ABBA IN QUIKAA)
C  BBBB : LIST 55  (UHF ONLY)
C  ABBA : LIST 58
C  BAAB : LIST 59  (UHF ONLY)
C  ABAB : LIST 56
C  BABA : LIST 57  (UHF ONLY)
C
CEND
C 
C  CODED SEPTEMBER/93 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL SORT
      DIMENSION ICORE(MAXCOR)
C
      COMMON/STATSYM/IRREPX
C
      CALL R2L2RNG(ICORE,MAXCOR,'ABBA',IUHF,IRREPX,R0)
      CALL R2L2RNG(ICORE,MAXCOR,'ABAB',IUHF,IRREPX,R0)
      IF(IUHF.EQ.1) THEN
       CALL R2L2RNG(ICORE,MAXCOR,'AAAA',IUHF,IRREPX,R0)
      ELSE
       CALL QUIKAA3(ICORE,MAXCOR ,1,54)
      ENDIF
      IF(IUHF.NE.0) THEN
       CALL R2L2RNG(ICORE,MAXCOR,'BBBB',IUHF,IRREPX,R0)
       CALL R2L2RNG(ICORE,MAXCOR,'BABA',IUHF,IRREPX,R0)
C
C  BAAB HAS BEEN CALCULATED ALREADY IN THE CALL WITH ABBA
C
      ENDIF
C
C RESORT H INTERMEDIATES
C
      IF(SORT)CALL SORTH(ICORE,MAXCOR,IUHF,54,1)
C
      RETURN
      END
