      SUBROUTINE R2L2Y1B(Y1,F1,ICORE,MAXCOR,IUHF)
C
C Y1(ai) = -1/2 F(na)*R(mn,ef)*L(mi,ef)
C
C        = -1/2 F(na)*G(ni)
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM
      DIMENSION ICORE(MAXCOR),Y1(*),F1(*)
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA ONE,ONEM/1.0D0,-1.0D0/
C
      IOFFF=1
      IOFFY=1
      DO 10 ISPIN=1,1+IUHF 
       I0G=1
       I000=I0G+IINTFP*NFMI(ISPIN)
C
C FIRST PICK UP G FROM LIST 191
C
       CALL GETLST(ICORE(I0G),1,1,1,ISPIN,191)
C
C FORM PRODUCT Y1(ai) = -F(an)*G(ni)
C
       IOFFG=I0G
       DO 11 IRREPI=1,NIRREP
        IRREPA=IRREPI
        IRREPN=IRREPA
        NUMA=VRT(IRREPA,ISPIN)
        NUMN=POP(IRREPN,ISPIN)
        NUMI=POP(IRREPI,ISPIN)
        CALL XGEMM('N','N',NUMA,NUMI,NUMN,ONEM,F1(IOFFF),NUMA,
     &             ICORE(IOFFG),NUMN,ONE,Y1(IOFFY),NUMA)
        IOFFF=IOFFF+IINTFP*NUMA*NUMN
        IOFFG=IOFFG+IINTFP*NUMN*NUMI
        IOFFY=IOFFY+IINTFP*NUMA*NUMI
11     CONTINUE
C
10    CONTINUE
C
      RETURN
      END
