      SUBROUTINE R2L2Y1D(Y1,ICORE,MAXCOR,IUHF)
C
C Y1(ai) = 1/2 R(mn,ef)*L(mn,ej)*W(gi,fa)
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR),Y1(*)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      I0G=1
      I000=I0G+IINTFP*(IRPDPD(1,19)+IUHF*IRPDPD(1,20))
      MXCOR=MAXCOR-I000+1
C
C FIRST PICK UP G(fg) FROM LIST 192
C
      CALL GETLST(ICORE(I0G),1,1,1,1,192)
      IF(IUHF.NE.0)THEN
       CALL GETLST(ICORE(I0G+IINTFP*IRPDPD(1,19)),1,1,1,2,192)
      ENDIF
C
C FORM PRODUCT Y(AI)= -W(Fa,Gi)*G(fg)
C
      CALL VMINUS(ICORE(I0G),IRPDPD(1,19)+IUHF*IRPDPD(1,20))
      CALL DVVINVO(1,Y1,ICORE(I0G),ICORE(I000),MXCOR,IUHF,27)
C
      RETURN
      END
