      SUBROUTINE SYM1718(ICORE,MAXCOR,IUHF,R0)
C
C SYMMETRIZE GAMMAS ON LISTS 117 AND 118
C
CEND 
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION HALF,ONE,R0
      DIMENSION ICORE(MAXCOR)
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA HALF,ONE /0.5D0,1.0D0/
C
      DO 40 IRREP=1,NIRREP 
       LIST1=118-IUHF
       LIST2=118
       DISSYG=IRPDPD(IRREP,ISYTYP(1,LIST1))
       NUMDSG=IRPDPD(IRREP,ISYTYP(2,LIST1))
       I000=1
       I010=I000+IINTFP*NUMDSG*DISSYG
       I020=I010+IINTFP*NUMDSG*DISSYG
       IF(IUHF.NE.0)THEN
        CALL GETLST(ICORE(I010),1,DISSYG,1,IRREP,LIST2)
        CALL TRANSP(ICORE(I010),ICORE(I000),DISSYG,NUMDSG)
        CALL GETLST(ICORE(I010),1,NUMDSG,1,IRREP,LIST1)
        CALL SAXPY (NUMDSG*DISSYG,ONE,ICORE(I000),1,ICORE(I010),1)
        CALL SSCAL (NUMDSG*DISSYG,HALF,ICORE(I010),1)
        CALL PUTLST(ICORE(I010),1,NUMDSG,1,IRREP,LIST1)
        CALL TRANSP(ICORE(I010),ICORE(I000),NUMDSG,DISSYG)
        CALL PUTLST(ICORE(I000),1,DISSYG,1,IRREP,LIST2)
       ELSE
        CALL GETLST(ICORE(I000),1,NUMDSG,1,IRREP,LIST2)
        CALL MPMT  (ICORE(I000),NUMDSG)
        CALL SSCAL (NUMDSG*DISSYG,HALF,ICORE(I000),1)
        CALL PUTLST(ICORE(I000),1,NUMDSG,1,IRREP,LIST2)
       ENDIF 
40    CONTINUE
C
      RETURN
      END
