      SUBROUTINE TPDIJKA(ICORE,MAXCOR,IUHF)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,CC,CCD,RCCD,DRCCD,LCCD,LCCSD,CC2
      DIMENSION ICORE(MAXCOR)
      COMMON/REFTYPE/MBPT2,CC,CCD,RCCD,DRCCD,LCCD,LCCSD,CC2
C
C DRIVER PROGRAM FOR THE G(IJ,KA) TERMS)
C
CEND
C
C CODED SEPTEMBER/93 JG
C
      CALL TPDIJKA1(ICORE,MAXCOR,IUHF)
C
      IF (CC) CALL TPDIJKA2(ICORE,MAXCOR,IUHF)
C
      CALL TPDIJKA3(ICORE,MAXCOR,IUHF)
C
      IF (CC .AND. .NOT. CC2) CALL TPDIJKA4(ICORE,MAXCOR,IUHF)
C
      IF (.NOT. CC2) CALL TPDIJKA5(ICORE,MAXCOR,IUHF)
C
      IF (CC .AND. .NOT. CC2) CALL TPDIJKA6(ICORE,MAXCOR,IUHF)
C
      IF (.NOT. CC2) CALL TPDIJKA7(ICORE,MAXCOR,IUHF)
C
      IF (CC) CALL TPDIJKA8(ICORE,MAXCOR,IUHF)
C
C ALL DONE, RETURN
C
      RETURN
      END
