      SUBROUTINE TPDIJAB(ICORE,MAXCOR,IUHF)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,CC,CCD,RCCD,DRCCD,LCCD,LCCSD,CC2
      LOGICAL SS, SD, DS, DD
      DIMENSION ICORE(MAXCOR)
C
      COMMON/REFTYPE/MBPT2,CC,CCD,RCCD,DRCCD,LCCD,LCCSD,CC2
      COMMON/DRVHBAR/SS, SD, DS, DD
C
C DRIVER PROGRAM FOR THE G(IJ,AB) TERMS)
C
CEND
C
C CODED OCTOBER/93 JG
C
C
C IJAB CONTRIBUTION ZERO 
C
      CALL TPDIJAB0(ICORE,MAXCOR,IUHF)
C
C IJAB CONTRIBUTIONS 1 TO 5
C
      IF (CC) CALL TPDIJAB1(ICORE,MAXCOR,IUHF)
C
      CALL TPDIJAB2(ICORE,MAXCOR,IUHF)
C
      CALL TPDIJAB3(ICORE,MAXCOR,IUHF)
C
      IF (CC .OR. DD) CALL TPDIJAB4(ICORE,MAXCOR,IUHF)
C
      IF (.NOT. CC2) CALL TPDIJAB5(ICORE,MAXCOR,IUHF) 
C
C ALL DONE, RETURN
C
      RETURN
      END
