      SUBROUTINE UPDATES(IRREPX,S,LIST0,IOFFSIN,LIST1,IUHF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION S(*)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      I0SA=1
      IF(IUHF.NE.0)THEN
       I0SB=I0SA+IRPDPD(IRREPX,9)
       I0SAB=I0SB+IRPDPD(IRREPX,10)
       I0SBB=I0SAB+IDSYMSZ(IRREPX,ISYTYP(1,46),ISYTYP(2,46))
       I0SAA=I0SBB+IDSYMSZ(IRREPX,ISYTYP(1,45),ISYTYP(2,45))
      ELSE
       I0SAB=I0SA+IRPDPD(IRREPX,9)
      ENDIF
C
      CALL PUTLST(S(I0SA),1,1,1,1+IOFFSIN,LIST1)
      CALL PUTALL(S(I0SAB),1,IRREPX,LIST0+2)
      IF(IUHF.NE.0)THEN
       CALL PUTLST(S(I0SB),1,1,1,2+IOFFSIN,LIST1)
       CALL PUTALL(S(I0SAA),1,IRREPX,LIST0)
       CALL PUTALL(S(I0SBB),1,IRREPX,LIST0+1)
      ENDIF
C
      RETURN
      END
