      SUBROUTINE WRITDG(DOO,DVV,DVO,DOV,LENOO,LENVV,LENVO,ISPIN,IOFF)
C
C WRITES DENSITY MATRIX TO DISK
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER POP,VRT,DIRPRD
      DIMENSION DOO(*),DVV(*),DVO(*),DOV(*)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
C 
      DATA ONE/1.0D0/
C
C OCC-OCC
C
      IOFFOO=1
      DO 10 IRREP=1,NIRREP
       LEN=POP(IRREP,ISPIN)
       CALL SYMMET2(DOO(IOFFOO),LEN)
       IOFFOO=IOFFOO+LEN*LEN
10    CONTINUE
      CALL PUTLST (DOO,IOFF,1,1,ISPIN,160)
C
C VRT-VRT
C
      IOFFVV=1
      DO 20 IRREP=1,NIRREP
       LEN=VRT(IRREP,ISPIN)
       CALL SYMMET2(DVV(IOFFVV),LEN)
       IOFFVV=IOFFVV+LEN*LEN
20    CONTINUE
      CALL PUTLST (DVV,IOFF,1,1,2+ISPIN,160)
C
C VRT-OCC
C
      CALL SAXPY  (LENVO,ONE,DVO,1,DOV,1)
      call sscal  (lenvo,0.5d0,dov,1)
      CALL PUTLST (DOV,IOFF,1,1,4+ISPIN,160)
C
      RETURN
      END
