      SUBROUTINE CALCFSTR(ROOT,FSTR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION TML(3),TMR(3),DIPSTR(3),OSCSTR(3)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA FACT0 /0.6666666666666666D0/
C
      ITHR=3*IINTFP
      CALL GETREC(20,'JOBARC','TMRIGHT ',ITHR,TMR)
      CALL GETREC(20,'JOBARC','TMLEFT  ',ITHR,TML)
      CALL GETREC(20,'JOBARC','TOTENERG',IINTFP,E)
CC
      DO 10 IXYZ=1,3
       DIPSTR(IXYZ)=TMR(IXYZ)*TML(IXYZ)
       OSCSTR(IXYZ)=FACT0*ROOT*DIPSTR(IXYZ)    
10    CONTINUE
C Peter 10/2010 recognized the problem here. 
CSSS      FSTR=SNRM2(3,OSCSTR,1)

      FSTR = DSQRT(OSCSTR(1) + OSCSTR(2) + OSCSTR(2))
C
      RETURN
      END
