      SUBROUTINE DIAGGUES(IRREPX,SCR,ISCR,MAXCOR,IUHF,NROOT)
C
C READ DIAGONAL ELEMENTS OF HAMILTONIAN MATRIX AND DETERMINE
C THE NROOT LOWEST LOCATIONS.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL PRINT
      CHARACTER*6 TYPE
      DIMENSION SCR(MAXCOR),ISCR(NROOT)
      COMMON/EXTRAP/MAXEXP,NREDUCE,NTOL,NSIZEC
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/FLAGS/IFLAGS(100) 
C
      PRINT=IFLAGS(1).GE.0
C
      LENSIN=0
      DO 5 I=1,1+IUHF
       LENSIN=IRPDPD(IRREPX,8+I)+LENSIN
5     CONTINUE
C
      IF(PRINT)THEN
       WRITE(6,1000)
       WRITE(6,1001)
       WRITE(6,1000)
      ENDIF
C
      I000=1
      I010=I000+NSIZEC
      I020=I010+NSIZEC
      I030=I020+NROOT
C
      CALL GETLST(SCR,1,1,1,1,472)
C
      DO 10 I=1,MIN(NROOT+3,NSIZEC)
       IPOS=IMINPOS(NSIZEC,SCR,1)
       CALL PUTLST(SCR(IPOS),I,1,1,IRREPX,95)
       IF(PRINT)THEN
        IF(IPOS.GT.LENSIN)THEN
         TYPE='Double'
        ELSE
         TYPE='Single'
        ENDIF
        WRITE(6,1003)I,SCR(IPOS),TYPE 
       ENDIF
       SCR(IPOS)=1.D+30
       CALL SYMT2AB(IRREPX,SCR,SCR(I020),MAXCOR-I020+1)
       ISCR(I)=IPOS
10    CONTINUE
C
      CALL PUTREC(20,'JOBARC','STRTGUES',NROOT,ISCR)
C
      IF(PRINT)WRITE(6,1000)
C
      RETURN
1000  FORMAT(T2,70('-'))
1001  FORMAT(T2,'Largest Diagonal Elements of Similarity-Transformed ',
     &          'Hamiltonian Matrix')
1002  FORMAT(T5,'Rank',T29,'Eigenvalue',T56,'Excitation Type')
1003  FORMAT(T5,I3,T26,F13.9,T61,A6)
      END       
