      SUBROUTINE DOZETA(ICORE,MAXCOR,IUHF,LENTOT)
C
C DRIVER FOR THE SOLUTION OF THE ZETA EQUATIONS THAT OCCUR IN
C EOM-CC GRADIENT THEORY.  TWO ALGORITHMS ARE AVAILABLE -- THE
C ORTHOGONAL SUBSPACE APPROACH OF POPLE AND THE DIIS METHOD DESCRIBED
C BY PULAY.  THE ALGORITHM IS SPECIFIED BY THE VALUE OF THE KEYWORD
C ZETA_TYPE, WHICH CAN BE EITHER "POPLE" OR "DIIS", WITH THE LATTER
C BEING THE DEFAULT.
C
CEND
      IMPLICIT INTEGER(A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON/FLAGS/IFLAGS(100)
      COMMON/FLAGS2/IFLAGS2(500)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      KMAX=IFLAGS(97)
      I000=1
      I010=I000+KMAX*KMAX*IINTFP
      I020=I010+KMAX*KMAX*IINTFP
      MXCOR=MAXCOR-I020+1
C
      IF(IFLAGS2(1).EQ.0)THEN
       CALL CALCZETA(ICORE(I020),MXCOR,IUHF,ICORE(I000),ICORE(I010),
     &               KMAX,LENTOT)
      ELSE
       CALL CLCZETA2(ICORE(I020),MXCOR,IUHF,ICORE(I000),ICORE(I010),
     &               KMAX,LENTOT,IFLAGS(88),IFLAGS2(2))
      ENDIF
C
      RETURN
      END
