      SUBROUTINE FORMQ1(IRREPX,ICORE,MAXCOR,IUHF)
C
C THIS ROUTINE FORMS THE FOLLOWING CONTRIBUTIONS TO THE THREE-BODY
C INTERMEDIATES:
C
C       Q(eb) = C(fm) * W(bm,ef)
C
C       Q(mj) = C(en) * W(mn,je)
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C ALLOCATE MEMORY FOR SINGLES (C) ARRAY AND TARGET ARRAYS
C
      LENCA=IRPDPD(IRREPX,9)
      LENCB=IRPDPD(IRREPX,10)
      LENQABA=IRPDPD(IRREPX,19)
      LENQABB=IRPDPD(IRREPX,20)
      LENQIJA=IRPDPD(IRREPX,21)
      LENQIJB=IRPDPD(IRREPX,22)
      I0CA=1
      I0QABA=I0CA+IINTFP*(LENCA+IUHF*LENCB)
      I0QIJA=I0QABA+IINTFP*(LENQABA+IUHF*LENQABB)
      I000 =I0QIJA+IINTFP*(LENQIJA+IUHF*LENQIJB)
      MXCOR=MAXCOR-I000+1
      CALL GETLST(ICORE(I0CA),1,1,1,1,490)
      IF(IUHF.NE.0)THEN
       I0CB=I0CA+IINTFP*LENCA
       CALL GETLST(ICORE(I0CB),1,1,1,2,490)
      ENDIF
C
      CALL IZERO  (ICORE(I0QABA),(LENQABA+IUHF*LENQABB)*IINTFP)
      CALL DVOINVV(IRREPX,ICORE(I0QABA),ICORE(I0CA),ICORE(I000),
     &             MXCOR,IUHF,27)
C
C TRANSPOSE C COEFFICIENTS
C
      CALL SYMTRA (IRREPX,VRT(1,1),POP(1,1),1,ICORE(I0CA),ICORE(I000))
      CALL SCOPY  (LENCA,ICORE(I000),1,ICORE(I0CA),1)
      IF(IUHF.NE.0)THEN
       CALL SYMTRA (IRREPX,VRT(1,2),POP(1,2),1,ICORE(I0CB),ICORE(I000))
       CALL SCOPY  (LENCB,ICORE(I000),1,ICORE(I0CB),1)
      ENDIF
      CALL IZERO  (ICORE(I0QIJA),(LENQIJA+IUHF*LENQIJB)*IINTFP)
      CALL DVOINOO(IRREPX,ICORE(I0QIJA),ICORE(I0CA),ICORE(I000),
     &             MXCOR,IUHF,7)
C
      CALL PUTLST(ICORE(I0QABA),1,1,1,1,492)
      CALL PUTLST(ICORE(I0QIJA),1,1,1,1,491)
      IF(IUHF.NE.0)THEN
       I0QABB=I0QABA+IINTFP*LENQABA
       I0QIJB=I0QIJA+IINTFP*LENQIJA
       CALL PUTLST(ICORE(I0QABB),1,1,1,2,492)
       CALL PUTLST(ICORE(I0QIJB),1,1,1,2,491)
      ENDIF
C
      RETURN
      END
