      SUBROUTINE GETDELE(IRREP,N,EDIFF,EVAL,POP,VRT,NOCC)
C
C   THIS ROUTINE CALCULATES 
C
C   EDIFF(AI) = (EI-EA)
C 
CEND
C
C CODED AUGUST/90 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER POP,VRT,DIRPRD
      DIMENSION EDIFF(N),EVAL(1),POP(8),VRT(8),IV(8)
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
C
C  CALCULATE FIRST OFFSET FOR THE VIRTUAL ORBITALS
C
      IV(1)=NOCC
      DO 1 IRREPJ=1,NIRREP-1
      IV(IRREPJ+1)=IV(IRREPJ)+VRT(IRREPJ)
1     CONTINUE
C
      IOFFP=0
C
C LOOP OVER THE IRREP OF THE OCCUPIED ORBITALS, THE
C IRREP OF THE VIRTUAL ORBITALS IS THEN SIMPLY GIVEN
C AS THE DIRECT PRODUCT OF IRREP WITh IRREPJ
C
      IND=0
      DO 10 IRREPJ=1,NIRREP
       IRREPI=DIRPRD(IRREP,IRREPJ)
       NOCCI=POP(IRREPJ)
       NVRTI=VRT(IRREPI)
       IOFFV=IV(IRREPI)
       DO 6 I=1,NOCCI
        INDI=I+IOFFP
        DO 5 IA=1,NVRTI
        INDA=IA+IOFFV
        IND=IND+1
        EDIFF(IND)=EVAL(INDI)-EVAL(INDA)
5      CONTINUE 
6      CONTINUE
       IOFFP=IOFFP+NOCCI
10    CONTINUE
      RETURN
      END
