      SUBROUTINE HBARDIG2(SCR,MAXCOR,IUHF,NSIZEC)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION SCR(MAXCOR),ONEM
      LOGICAL MBPT2,CC,CCD,RPA,DRPA,LCCD,LCCSD,CC2
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8) 
      COMMON /REFTYPE/ MBPT2,CC,CCD,RPA,DRPA,LCCD,LCCSD,CC2
C
      DATA ONEM /-1.0D0/
C
      CALL DDENOM(SCR,MAXCOR/2,IUHF,1,63)
      IF (.NOT. CC2) CALL DDENOM2(SCR,MAXCOR/2,IUHF,1,63)
C
C SINGLES PART
C
      IOFFC=1
      DO 10 ISPIN=1,1+IUHF
       LISTW=53+ISPIN
       NDIM=IRPDPD(1,8+ISPIN)
       ISCR=IOFFC+NDIM
       CALL GETLST(SCR(ISCR),1,NDIM,1,1,LISTW)
       CALL GETLST(SCR(IOFFC),1,1,1,9,63+ISPIN)
       CALL VMINUS(SCR(IOFFC),NDIM)
       CALL SAXPY (NDIM,ONEM,SCR(ISCR),NDIM+1,SCR(IOFFC),1)
       IOFFC=ISCR
10    CONTINUE
C
C DOUBLES PART
C
      DO 20 ISPIN=3,3-2*IUHF,-1
       LISTD=63+ISPIN
       DO 30 IRREPR=1,NIRREP
        IRREPL=DIRPRD(IRREPR,1)
        NUMDIS=IRPDPD(IRREPR,ISYTYP(2,LISTD))
        DISSIZ=IRPDPD(IRREPL,ISYTYP(1,LISTD))
        CALL GETLST(SCR(IOFFC),1,NUMDIS,1,IRREPR,LISTD)
        CALL VMINUS(SCR(IOFFC),NUMDIS*DISSIZ)
        IOFFC=IOFFC+NUMDIS*DISSIZ
30     CONTINUE
20    CONTINUE
C
      CALL PUTLST(SCR,1,1,1,1,88)
C
      RETURN
      END
