
      SUBROUTINE LARGE(NLARGE,LENGTH,V,TMP,ITMP)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION V(LENGTH,LENGTH),TMP(LENGTH*LENGTH)
      DIMENSION ITMP(LENGTH*LENGTH)
      IGETI(IX,N)=1+(IX-1)/N
      IGETA(IX,N)=IX-(IGETI(IX,N)-1)*N
C
      CALL FINDMAX(NLARGE,V,LENGTH*LENGTH,TMP,ITMP)
C
      WRITE(6,100)
      WRITE(6,101)
      WRITE(6,100)
      DO 10 I=1,NLARGE
       JLOC=IGETI(ITMP(I),LENGTH)
       ILOC=IGETA(ITMP(I),LENGTH)
       WRITE(6,'(4X,2I5,F20.10)')ILOC,JLOC,TMP(I)
10    CONTINUE
      WRITE(6,100)
C
100   FORMAT(4X,40('-'))
101   FORMAT(T9,'I',T14,'J',T28,'Value')
C
      RETURN
      END  
