      SUBROUTINE MKSD(IRREPX,S,LIST20,LIST1,IOFFSIN,IUHF)
C
C     This subroutine is a hacked up version of UPDATES. It takes a
C     singles and doubles R or L vector and puts it on specified lists.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,POP,VRT,DISSIZ,DISSYT
      DIMENSION S(*)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/EXTRAP/MAXEXP,NREDUCE,NTOL,NSIZEC
      COMMON/SYMLOC/ISYMOFF(8,8,25)
C
      DATA TWO,ONE,ONEM,ZILCH /2.0D0,1.0D0,-1.0D0,0.0D0/
C
      I0SA=1
      IF(IUHF.NE.0)THEN
       I0SB=I0SA+IRPDPD(IRREPX,9)
       I0SAB=I0SB+IRPDPD(IRREPX,10)
       I0SBB=I0SAB+IDSYMSZ(IRREPX,ISYTYP(1,46),ISYTYP(2,46))
       I0SAA=I0SBB+IDSYMSZ(IRREPX,ISYTYP(1,45),ISYTYP(2,45))
      ELSE
       I0SAB=I0SA+IRPDPD(IRREPX,9)
      ENDIF
C
      CALL PUTLST(S(I0SA),1,1,1,1+IOFFSIN,LIST1)
      CALL PUTALL(S(I0SAB),1,IRREPX,LIST20+2)

CSSS      length = IDSYMSZ(IRREPX,ISYTYP(1,46),ISYTYP(2,46))
CSSS      Write(6, "(5(F10.6))") (S(I0SAB+kk), kk=0, length-1)
CSSS      write(6,*) LIST20+2, IRREPX,
CSSS     &            IDSYMSZ(IRREPX,ISYTYP(1,46),ISYTYP(2,46))
CSSS      call checksum("MKSD", S(I0SAB),
CSSS     &               IDSYMSZ(IRREPX,ISYTYP(1,46),ISYTYP(2,46)),sum)
C
      IF(IUHF.NE.0)THEN
       CALL PUTLST(S(I0SB),1,1,1,2+IOFFSIN,LIST1)
       CALL PUTALL(S(I0SAA),1,IRREPX,LIST20)
       CALL PUTALL(S(I0SBB),1,IRREPX,LIST20+1)
CSSS      call checksum("MKSD", S(I0SBB),
CSSS     &               IDSYMSZ(IRREPX,ISYTYP(1,45),ISYTYP(2,45)),sum)
CSSS      call checksum("MKSD", S(I0SAA),
CSSS     &               IDSYMSZ(IRREPX,ISYTYP(1,44),ISYTYP(2,44)),sum)
      ENDIF

      RETURN
      END
