      SUBROUTINE MTDAENER(ICORE,MAXCOR,IUHF,IRREPX,DENSITY,ETDA)
      IMPLICIT INTEGER (A-Z)
      LOGICAL DENSITY
      DOUBLE PRECISION ONE,ONEM,ZILCH,SDOT,DFLOAT,ESCF,E2,ETOTCISD
      DOUBLE PRECISION FACT,SSUM,ETOT,ETDA,ED,NORM1,ED1,ED2
      DOUBLE PRECISION ED3,ED4,ED5
      
      DOUBLE PRECISION SNRM2
      DIMENSION ICORE(MAXCOR),IDOO(2),IDVV(2),I0L(2),I0R(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      DATA ONE,ONEM,ZILCH /1.0D0,-1.0D0,0.0D0/
      ED=ZILCH
      ED1=ZILCH
      ED2=ZILCH
      ED3=ZILCH
      ED4=ZILCH
      ED5=ZILCH
      FACT=ONE+DFLOAT(1-IUHF)
      IDOO(1)=1
      IDOO(2)=IDOO(1)+IUHF*IINTFP*NFMI(1)
      IDVV(1)=IDOO(2)+IINTFP*NFMI(2)
      IDVV(2)=IDVV(1)+IUHF*IINTFP*NFEA(1)
      I0L (1)=IDVV(2)+IINTFP*NFEA(2)
      I0L (2)=I0L(1) +IUHF*IINTFP*IRPDPD(IRREPX,9)
      I0R (1)=I0L(2) +IINTFP*IRPDPD(IRREPX,10)
      I0R (2)=I0R(1) +IUHF*IINTFP*IRPDPD(IRREPX,9)
      I000   =I0R(2)+IINTFP*IRPDPD(IRREPX,10)
      MXCOR  =MAXCOR-I000+1
      IF(DENSITY)THEN
       DO 10 ISPIN=1,1+IUHF
        CALL GETLST(ICORE(IDOO(ISPIN)),1,1,1,ISPIN,160)
        CALL GETLST(ICORE(IDVV(ISPIN)),1,1,1,ISPIN+2,160)
10     CONTINUE
       CALL GETLST(ETDA,1,1,1,IRREPX,95)
      ELSE
       DO 11 ISPIN=1,1+IUHF
        CALL GETLST(ICORE(I0R(ISPIN)),1,1,1,ISPIN,490)
        CALL ZERO(ICORE(I000),NFMI(ISPIN))
        CALL MODGIJ(1,IRREPX,IRREPX,ICORE(IDOO(ISPIN)),ICORE(I000),
     &              ICORE(I0R(ISPIN)),ICORE(I0R(ISPIN)),ISPIN,ONEM)
        CALL ZERO(ICORE(I000),NFEA(ISPIN))
        CALL MODGAB(1,IRREPX,IRREPX,ICORE(IDVV(ISPIN)),ICORE(I000),
     &              ICORE(I0R(ISPIN)),ICORE(I0R(ISPIN)),ISPIN,ONE)
11     CONTINUE
      ENDIF
       
      CALL GFORMG(1,1,44,14,0,ICORE(I000),MAXCOR,0,ONE,ONE,IUHF)
      DO 20 ISPIN=1,1+IUHF
       CALL GETLST(ICORE(I000),1,1,1,ISPIN,91)
       ED1=ED1+FACT*SDOT(NFMI(ISPIN),ICORE(I000),1,ICORE(IDOO(ISPIN)),1)
       Write(6,*) ED1
       CALL GETLST(ICORE(I000),1,1,1,ISPIN,92)
       ED2=ED2+FACT*SDOT(NFEA(ISPIN),ICORE(I000),1,ICORE(IDVV(ISPIN)),1)
       Write(6,*) ED2
20    CONTINUE
      DO 21 ISPIN=3,3-2*IUHF,-1
       LISTC2=443+ISPIN
       CALL NEWTYP2(IRREPX,LISTC2,ISYTYP(1,LISTC2),ISYTYP(2,LISTC2),
     &              .TRUE.)
       CALL ZEROLIST(ICORE(I000),MXCOR,LISTC2)
21    CONTINUE
      CALL DT1INT2A_EXT(ICORE(I000),MXCOR,IUHF,IRREPX,1,490,0, 7,444,
     &              .FALSE.)
      CALL DT1INT2B_EXT(ICORE(I000),MXCOR,IUHF,IRREPX,1,490,0,27,444,
     &              .FALSE.)
      NORM1=ZILCH
      DO 30 ISPIN=3,3-2*IUHF,-1
       LISTD=447+ISPIN
       LISTC2=443+ISPIN
       ISIZE=IDSYMSZ(IRREPX,ISYTYP(1,LISTD),ISYTYP(2,LISTD))
       ISIZE=IDSYMSZ(IRREPX,ISYTYP(1,LISTC2),ISYTYP(2,LISTC2))
       I010=I000+IINTFP*ISIZE
       I020=I010+IINTFP*ISIZE
       CALL GETALL(ICORE(I000),ISIZE,IRREPX,LISTC2)
       CALL GETALL(ICORE(I010),ISIZE,IRREPX,LISTD)
       CALL VECDIV2(-ETDA,ICORE(I000),ICORE(I010),ICORE(I000),ISIZE)
       CALL VMINUS (ICORE(I000),ISIZE)
       CALL PUTALL (ICORE(I000),ISIZE,IRREPX,LISTC2)
       CALL SCOPY (ISIZE,ICORE(I000),1,ICORE(I010),1)
       IF(IUHF.EQ.0)THEN
        IOFF=I000
        ITMP1=I020
        DO 31 IRREPR=1,NIRREP
         IRREPL=DIRPRD(IRREPR,IRREPX)
         NUMDIS=IRPDPD(IRREPR,ISYTYP(2,LISTD))
         DISSIZ=IRPDPD(IRREPL,ISYTYP(1,LISTD))
         ITMP2=ITMP1+IINTFP*MAX(DISSIZ,NUMDIS)
         CALL SPINAD1(IRREPR,POP,DISSIZ,ICORE(IOFF),ICORE(ITMP1),
     &               ICORE(ITMP2))
         IOFF=IOFF+IINTFP*NUMDIS*DISSIZ
31      CONTINUE       
       ENDIF
       CALL VECPRD(ICORE(I000),ICORE(I010),ICORE(I000),ISIZE)
       NORM1=NORM1+SSUM(ISIZE,ICORE(I000),1)
       CALL GETALL(ICORE(I010),ISIZE,IRREPX,LISTD)
       ED3=ED3+SDOT(ISIZE,ICORE(I000),1,ICORE(I010),1)
       CALL SSCAL(ISIZE,ETDA,ICORE(I000),1)
       ED3=ED3+SSUM(ISIZE,ICORE(I000),1)
30    CONTINUE
      Write(6,*) ED3
      CALL RESORT(ICORE(I000),MXCOR,IUHF,1,44,34)
      CALL GT2XF(ICORE(I0R(1)),1,IRREPX,34,490,0,ICORE(I000),
     &           MXCOR,IUHF,0)
      CALL RESORT(ICORE(I000),MXCOR,IUHF,1,14,34)
      CALL GT2XF(ICORE(I0L(1)),1,IRREPX,34,490,0,ICORE(I000),
     &           MXCOR,IUHF,0)
      DO 40 ISPIN=1,1+IUHF
       LENGTH=IRPDPD(IRREPX,8+ISPIN)
       ED5=ED5+FACT*SDOT(LENGTH,ICORE(I0L(ISPIN)),1,ICORE(I0R(ISPIN)),1)
40    CONTINUE  
      WRITE(6,*) ED5
      Write(6,"(a,1x,F15.9)") " The Doubles correction:",ED1+ED2+ED3+ED5
      ETOT=ETDA+ED1+ED2+ED3+ED5
      CALL GETREC(20,'JOBARC','SCFENEG ',IINTFP,ESCF)
      CALL GETREC(20,'JOBARC','TOTENERG',IINTFP,E2)
      WRITE(6,1000)ETOT
1000  FORMAT(T3,' Total CIS(D) excitation energy : ',F22.14,' a.u.')
      WRITE(6,1001)ETOT+E2
1001  FORMAT(T3,' Total CIS(D) energy : ',F22.14,' a.u.')
      WRITE(6,1002)ONE/(ONE+NORM1)**2
1002  FORMAT(T3,' <CIS(D)|S><S|CIS(D)> = ',F10.7)
      ETOTCISD=ETOT+E2
      CALL PUTREC(20,'JOBARC','TOTENER2',IINTFP,ETOTCISD)
      RETURN
      END
