      SUBROUTINE TRUNCATE(EVAL,EVEC,EVALSEL,EVECSEL,SCR,MAXCOR,NDIMVEC,
     &   NDIMOLD,NDIMNEW,IRREPX,ISIDE, IUHF,ICOLSCR)
C
C THIS ROUTINE REDUCES THE DIMENSION OF THE CI EXPANSION BASIS
C BY PERFORMING A LINEAR TRANSFORMATION OF THE EXPANSION VECTORS.
C
C  NDIMNEW MAY BE CHANGED IN THIS PROCEDURE. ONLY REAL EIGENVALUES
C  ARE ALLOWED (EVAL < 1000, SAY, IMAGINARY EIGENVALUES WERE PUT TO
C  1.E12 OR SO. IF THERE ARE NOT ENOUGH REAL EIGENVALUES AVAILABLE
C  NDIMNEW IS LOWERED.
C
CEND
      IMPLICIT INTEGER (A-Z)
      PARAMETER (MAXORD=100)
      LOGICAL PRINT
      CHARACTER*1 NATURE(100,8)
      DOUBLE PRECISION EVEC(NDIMOLD,NDIMOLD),EVECSEL(NDIMOLD,NDIMNEW),
     $   SCR(MAXCOR), EVALSEL(NDIMNEW), EVAL(NDIMOLD)
      DOUBLE PRECISION RESID2, XCLOSE, ROOT, EIGVAL, OSCSTR,
     &                 EIGVAL_T
      DOUBLE PRECISION OVRLAP, RESID
C
      COMMON/EXTINF/NDIMR,IOLDEST
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/ROOTS/EIGVAL(100,8),EIGVAL_T(100,8),OSCSTR(100,8),
     &             BGN(100,8),BGN_IRP(100,8),END(100,8),
     &             END_IRP(100,8),NATURE
      COMMON/EXTINF2/ROOT,OVRLAP,RESID
      COMMON/EXTINF3/IROOT,LOCROOT,ITROOT
C
      DATA ONE,ZILCH /1.0D0,0.0D0/
C
      PRINT=.FALSE.
C
C  SELECT EIGENVECTORS THAT WILL BE RETAINED IN TRUNCATED SPACE
C  FIRST FIND CURRENT EIGENVECTOR AND ALREADY FOUND VECTORS
C
      CALL SCOPY(NDIMOLD,EVAL,1,EVALSEL,1)
      ICOUNT = 0
      CALL FNDCLOSE(NDIMOLD,EVAL,ROOT, XCLOSE,ICLOSE)
      ICOUNT = ICOUNT + 1
      CALL SCOPY(NDIMOLD,EVEC(1,ICLOSE),1,EVECSEL(1,ICOUNT),1)
      EVALSEL(ICOUNT) = XCLOSE
      EVAL(ICLOSE) = 1.0D30
         DO 10 I = MIN(NDIMNEW-1,IROOT),1, -1
            CALL FNDCLOSE(NDIMOLD,EVAL,
     $         EIGVAL(I,IRREPX),XCLOSE,ICLOSE)
            ICOUNT = ICOUNT + 1
            CALL SCOPY(NDIMOLD,EVEC(1,ICLOSE),1,EVECSEL(1,ICOUNT),1)
            EVALSEL(ICOUNT) = XCLOSE
            EVAL(ICLOSE) = 1.0D30
 10      CONTINUE
C
C  NEXT RETAIN EIGENVALUES CLOSE TO ROOT
C
      DO 20 I = 1, NDIMNEW - IROOT - 1
         CALL FNDCLOSE(NDIMOLD,EVAL,ROOT, XCLOSE,ICLOSE)
         ICOUNT = ICOUNT + 1
         CALL SCOPY(NDIMOLD,EVEC(1,ICLOSE),1,EVECSEL(1,ICOUNT),1)
         EVALSEL(ICOUNT) = XCLOSE
         EVAL(ICLOSE) = 1.0D30
 20      CONTINUE
C
C  CHECK IF ALL RETAINED EIGENVALUES ARE MEANINGFUL (REAL ORIGINALLY)
C
 25      IF (EVALSEL(NDIMNEW) .GT. 1000.0) THEN
            NDIMNEW = NDIMNEW - 1
            IF (NDIMNEW .GE. 1) THEN
               GO TO 25
            ELSE
               WRITE(6,*) 'SOMETHING WRONG IN TRUNCATE '
               WRITE(6,*) ' SELECTED EIGENVALUES '
               DO 26 I = 1, NDIMOLD
                  WRITE(6,*) EVALSEL(I)
 26            CONTINUE
            ENDIF
         ENDIF
C
         CALL SCOPY(NDIMNEW,EVALSEL,1,EVAL,1)
C
C SCHMIDT ORTHOGONALIZE EXPANSION VECTORS
C
      DO 30 I=2,NDIMNEW
       CALL GSCHMIDT(EVECSEL(1,I),EVECSEL,NDIMOLD,I-1,SCR,RESID2)
 30   CONTINUE
C
C
C CARRY OUT TRANSFORMATION TO NEW SPACE
C
      CALL TRNSPACE(NDIMVEC,NDIMNEW,NDIMOLD,SCR,EVECSEL,MAXCOR,IRREPX,
     &   ISIDE,470,.TRUE.,MAXORD,IOLDEST,PRINT,IUHF,ICOLSCR)
      CALL TRNSPACE(NDIMVEC,NDIMNEW,NDIMOLD,SCR,EVECSEL,MAXCOR,IRREPX,
     &   ISIDE,471,.FALSE.,MAXORD,IOLDEST,PRINT,IUHF,ICOLSCR)
C
C TRANSFORM LASTVECT TO NEW BASIS
C
       I000=1
       I010=I000+100
       I020=I010+100
       CALL ZERO(SCR(I010),100)
       SCR(I010 + 1) = ONE
C       CALL GETREC(20,'JOBARC','LASTVECT',100*IINTFP,SCR)
C       CALL XGEMM('N','N',1,NDIMNEW,NDIMOLD,ONE,SCR(2),1,EVECSEL,
C     &    NDIMOLD, ZILCH,SCR(I010+1),1)
       CALL PUTREC(20,'JOBARC','LASTVECT',100*IINTFP,SCR(I010))
C 
       WRITE(6,2000) NDIMNEW
2000   FORMAT(T3,' Expansion vector space truncated to ',
     &           'dimension ',I3,'.')
C
      RETURN
1000  FORMAT(T3,'@TRUNCATE-F, Insufficient core to truncate expansion ',
     &          'space.')
      END

